"""Searchable copy of airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_creatives.json (part 2 of 2) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_creatives.json'
PART = 2
TOTAL_PARTS = 2

CONTENT = """\
            "offer_id": {
              "type": ["null", "string"]
            },
            "page_welcome_message": {
              "type": ["null", "string"]
            },
            "retailer_item_ids": {
              "type": ["null", "array"],
              "items": {
                "type": "string"
              }
            },
            "show_multiple_images": {
              "type": ["null", "boolean"]
            }
          },
          "type": ["null", "object"]
        },
        "text_data": {
          "type": ["null", "object"],
          "properties": {
            "message": {
              "type": "string"
            }
          }
        },
        "video_data": {
          "type": ["null", "object"],
          "properties": {
            "additional_image_index": {
              "type": ["null", "integer"]
            },
            "branded_content_sponsor_page_id": {
              "type": ["null", "string"]
            },
            "branded_content_sponsor_relationship": {
              "type": ["null", "string"]
            },
            "call_to_action": {
              "properties": {
                "value": {
                  "properties": {
                    "app_destination": {
                      "type": ["null", "string"]
                    },
                    "app_link": {
                      "type": ["null", "string"]
                    },
                    "application": {
                      "type": ["null", "string"]
                    },
                    "event_id": {
                      "type": ["null", "string"]
                    },
                    "lead_gen_form_id": {
                      "type": ["null", "string"]
                    },
                    "link": {
                      "type": ["null", "string"]
                    },
                    "link_caption": {
                      "type": ["null", "string"]
                    },
                    "link_format": {
                      "type": ["null", "string"]
                    },
                    "page": {
                      "type": ["null", "string"]
                    },
                    "product_link": {
                      "type": ["null", "string"]
                    }
                  },
                  "type": ["null", "object"]
                },
                "type": {
                  "type": ["null", "string"]
                }
              },
              "type": ["null", "object"]
            },
            "image_hash": {
              "type": ["null", "string"]
            },
            "image_url": {
              "type": ["null", "string"]
            },
            "link_description": {
              "type": ["null", "string"]
            },
            "message": {
              "type": ["null", "string"]
            },
            "offer_id": {
              "type": ["null", "string"]
            },
            "page_welcome_message": {
              "type": ["null", "string"]
            },
            "retailer_item_ids": {
              "type": ["null", "array"],
              "items": {
                "type": "string"
              }
            },
            "targeting": {
              "$ref": "targeting.json"
            },
            "title": {
              "type": ["null", "string"]
            },
            "video_id": {
              "type": ["null", "string"]
            }
          }
        }
      },
      "type": ["null", "object"]
    },
    "object_type": {
      "description": "Type of object associated with the ad creative.",
      "type": ["null", "string"]
    },
    "object_url": {
      "description": "URL of the associated object.",
      "type": ["null", "string"]
    },
    "product_set_id": {
      "description": "ID of the product set linked to the ad creative.",
      "type": ["null", "string"]
    },
    "source_instagram_media_id": {
      "type": ["null", "string"]
    },
    "status": {
      "description": "Status of the ad creative.",
      "type": ["null", "string"]
    },
    "template_url": {
      "description": "URL of the template used in the ad creative.",
      "type": ["null", "string"]
    },
    "template_url_spec": {
      "description": "Specification for the template URL.",
      "type": ["null", "object"],
      "properties": {
        "android": {
          "type": ["null", "object"],
          "properties": {
            "app_name": {
              "type": "string"
            },
            "package": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        },
        "config": {
          "type": ["null", "object"],
          "properties": {
            "app_id": {
              "type": "string"
            }
          }
        },
        "ios": {
          "type": ["null", "object"],
          "properties": {
            "app_name": {
              "type": "string"
            },
            "app_store_id": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        },
        "ipad": {
          "type": ["null", "object"],
          "properties": {
            "app_name": {
              "type": "string"
            },
            "app_store_id": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        },
        "iphone": {
          "type": ["null", "object"],
          "properties": {
            "app_name": {
              "type": "string"
            },
            "app_store_id": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        },
        "web": {
          "type": ["null", "object"],
          "properties": {
            "should_fallback": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        },
        "windows_phone": {
          "type": ["null", "object"],
          "properties": {
            "app_id": {
              "type": "string"
            },
            "app_name": {
              "type": "string"
            },
            "url": {
              "type": "string"
            }
          }
        }
      }
    },
    "thumbnail_data_url": {
      "description": "URL of the thumbnail data.",
      "type": ["null", "string"]
    },
    "thumbnail_url": {
      "description": "URL of the thumbnail image.",
      "type": ["null", "string"]
    },
    "image_hash": {
      "description": "Hash value representing the image used in the ad creative.",
      "type": ["null", "string"]
    },
    "url_tags": {
      "description": "Tags added to the URL of the ad creative.",
      "type": ["null", "string"]
    },
    "video_id": {
      "description": "ID of the video used in the ad creative.",
      "type": ["null", "string"]
    },
    "link_url": {
      "description": "URL associated with the ad creative.",
      "type": ["null", "string"]
    }
  },
  "type": ["null", "object"]
}
"""
