"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/chatplugin.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/chatplugin.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "alignment": {
      "type": ["string", "null"]
    },
    "desktop_bottom_spacing": {
      "type": ["string", "null"]
    },
    "desktop_side_spacing": {
      "type": ["string", "null"]
    },
    "entry_point_icon": {
      "type": ["string", "null"]
    },
    "entry_point_label": {
      "type": ["string", "null"]
    },
    "greeting_dialog_display": {
      "type": ["string", "null"]
    },
    "guest_chat_mode": {
      "type": ["string", "null"]
    },
    "mobile_bottom_spacing": {
      "type": ["string", "null"]
    },
    "mobile_chat_display": {
      "type": ["string", "null"]
    },
    "mobile_side_spacing": {
      "type": ["string", "null"]
    },
    "theme_color": {
      "type": ["string", "null"]
    },
    "welcome_screen_greeting": {
      "type": ["string", "null"]
    }
  }
}
"""
