"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/commercemerchantsettingssetupstatus.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/commercemerchantsettingssetupstatus.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "deals_setup": {
      "type": ["string", "null"]
    },
    "marketplace_approval_status": {
      "type": ["string", "null"]
    },
    "marketplace_approval_status_details": {
      "type": ["string", "null"]
    },
    "payment_setup": {
      "type": ["string", "null"]
    },
    "review_status": {
      "type": ["string", "null"]
    },
    "shop_setup": {
      "type": ["string", "null"]
    }
  }
}
"""
