"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/coverphoto.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/coverphoto.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "cover_id": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "offset_x": {
      "type": ["number", "null"]
    },
    "offset_y": {
      "type": ["number", "null"]
    },
    "source": {
      "type": ["string", "null"]
    }
  }
}
"""
