"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/customusersettings.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/customusersettings.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {}
}
"""
