"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/engagement.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/engagement.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "count": {
      "type": ["integer", "null"]
    },
    "count_string": {
      "type": ["string", "null"]
    },
    "count_string_with_like": {
      "type": ["string", "null"]
    },
    "count_string_without_like": {
      "type": ["string", "null"]
    },
    "social_sentence": {
      "type": ["string", "null"]
    },
    "social_sentence_with_like": {
      "type": ["string", "null"]
    },
    "social_sentence_without_like": {
      "type": ["string", "null"]
    }
  }
}
"""
