"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/group.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/group.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "archived": {
      "type": ["boolean", "null"]
    },
    "created_time": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "description": {
      "type": ["string", "null"]
    },
    "email": {
      "type": ["string", "null"]
    },
    "icon": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "link": {
      "type": ["string", "null"]
    },
    "member_count": {
      "type": ["integer", "null"]
    },
    "member_request_count": {
      "type": ["integer", "null"]
    },
    "name": {
      "type": ["string", "null"]
    },
    "parent": {
      "type": ["string", "null"]
    },
    "permissions": {
      "type": ["array", "null"],
      "items": {
        "type": ["string", "null"]
      }
    },
    "privacy": {
      "type": ["string", "null"]
    },
    "purpose": {
      "type": ["string", "null"]
    },
    "subdomain": {
      "type": ["string", "null"]
    },
    "updated_time": {
      "type": ["string", "null"],
      "format": "date-time"
    }
  }
}
"""
