"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/imagecopyright.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/imagecopyright.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "artist": {
      "type": ["string", "null"]
    },
    "copyright_monitoring_status": {
      "type": ["string", "null"]
    },
    "creation_time": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "creator": {
      "type": ["string", "null"]
    },
    "custom_id": {
      "type": ["string", "null"]
    },
    "description": {
      "type": ["string", "null"]
    },
    "filename": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "matches_count": {
      "type": ["integer", "null"]
    },
    "original_content_creation_date": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "tags": {
      "type": ["array", "null"],
      "items": {
        "type": ["string", "null"]
      }
    },
    "title": {
      "type": ["string", "null"]
    },
    "update_time": {
      "type": ["string", "null"],
      "format": "date-time"
    }
  }
}
"""
