"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/insightsresult.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/insightsresult.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "description": {
      "type": ["string", "null"]
    },
    "description_from_api_doc": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "name": {
      "type": ["string", "null"]
    },
    "period": {
      "type": ["string", "null"]
    },
    "title": {
      "type": ["string", "null"]
    }
  }
}
"""
