"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/instagramuser.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/instagramuser.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "follow_count": {
      "type": ["integer", "null"]
    },
    "followed_by_count": {
      "type": ["integer", "null"]
    },
    "has_profile_picture": {
      "type": ["boolean", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "is_private": {
      "type": ["boolean", "null"]
    },
    "is_published": {
      "type": ["boolean", "null"]
    },
    "media_count": {
      "type": ["integer", "null"]
    },
    "profile_pic": {
      "type": ["string", "null"]
    },
    "username": {
      "type": ["string", "null"]
    }
  }
}
"""
