"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/location.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/location.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "city": {
      "type": ["string", "null"]
    },
    "city_id": {
      "type": ["integer", "null"]
    },
    "country": {
      "type": ["string", "null"]
    },
    "country_code": {
      "type": ["string", "null"]
    },
    "latitude": {
      "type": ["number", "null"]
    },
    "located_in": {
      "type": ["string", "null"]
    },
    "longitude": {
      "type": ["number", "null"]
    },
    "name": {
      "type": ["string", "null"]
    },
    "region": {
      "type": ["string", "null"]
    },
    "region_id": {
      "type": ["integer", "null"]
    },
    "state": {
      "type": ["string", "null"]
    },
    "street": {
      "type": ["string", "null"]
    },
    "zip": {
      "type": ["string", "null"]
    }
  }
}
"""
