"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/mailingaddress.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/mailingaddress.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "city": {
      "type": ["string", "null"]
    },
    "country": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "postal_code": {
      "type": ["string", "null"]
    },
    "region": {
      "type": ["string", "null"]
    },
    "street1": {
      "type": ["string", "null"]
    },
    "street2": {
      "type": ["string", "null"]
    }
  }
}
"""
