"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/mediafingerprint.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/mediafingerprint.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "duration_in_sec": {
      "type": ["number", "null"]
    },
    "fingerprint_content_type": {
      "type": ["string", "null"]
    },
    "fingerprint_type": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "metadata": {
      "type": ["string", "null"]
    },
    "title": {
      "type": ["string", "null"]
    },
    "universal_content_id": {
      "type": ["string", "null"]
    }
  }
}
"""
