"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/messagingfeaturestatus.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/messagingfeaturestatus.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "hop_v2": {
      "type": ["boolean", "null"]
    }
  }
}
"""
