"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagepaymentoptions.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagepaymentoptions.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "amex": {
      "type": ["integer", "null"]
    },
    "cash_only": {
      "type": ["integer", "null"]
    },
    "discover": {
      "type": ["integer", "null"]
    },
    "mastercard": {
      "type": ["integer", "null"]
    },
    "visa": {
      "type": ["integer", "null"]
    }
  }
}
"""
