"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagesettings.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagesettings.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "setting": {
      "type": ["string", "null"]
    },
    "value": {
      "type": ["string", "null"]
    }
  }
}
"""
