"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagecalltoaction.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagecalltoaction.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "android_deeplink": {
      "type": ["string", "null"]
    },
    "android_destination_type": {
      "type": ["string", "null"]
    },
    "android_package_name": {
      "type": ["string", "null"]
    },
    "android_url": {
      "type": ["string", "null"]
    },
    "created_time": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "email_address": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "intl_number_with_plus": {
      "type": ["string", "null"]
    },
    "iphone_deeplink": {
      "type": ["string", "null"]
    },
    "iphone_destination_type": {
      "type": ["string", "null"]
    },
    "iphone_url": {
      "type": ["string", "null"]
    },
    "status": {
      "type": ["string", "null"]
    },
    "type": {
      "type": ["string", "null"]
    },
    "updated_time": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "web_destination_type": {
      "type": ["string", "null"]
    },
    "web_url": {
      "type": ["string", "null"]
    }
  }
}
"""
