"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagerestaurantservices.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/pagerestaurantservices.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "catering": {
      "type": ["boolean", "null"]
    },
    "delivery": {
      "type": ["boolean", "null"]
    },
    "groups": {
      "type": ["boolean", "null"]
    },
    "kids": {
      "type": ["boolean", "null"]
    },
    "outdoor": {
      "type": ["boolean", "null"]
    },
    "pickup": {
      "type": ["boolean", "null"]
    },
    "reserve": {
      "type": ["boolean", "null"]
    },
    "takeout": {
      "type": ["boolean", "null"]
    },
    "waiter": {
      "type": ["boolean", "null"]
    },
    "walkins": {
      "type": ["boolean", "null"]
    }
  }
}
"""
