"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/place.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/place.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "id": {
      "type": ["string", "null"]
    },
    "name": {
      "type": ["string", "null"]
    },
    "overall_rating": {
      "type": ["number", "null"]
    }
  }
}
"""
