"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/privacy.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/privacy.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "allow": {
      "type": ["string", "null"]
    },
    "deny": {
      "type": ["string", "null"]
    },
    "description": {
      "type": ["string", "null"]
    },
    "friends": {
      "type": ["string", "null"]
    },
    "networks": {
      "type": ["string", "null"]
    },
    "value": {
      "type": ["string", "null"]
    }
  }
}
"""
