"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/productcatalog.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/productcatalog.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "default_image_url": {
      "type": ["string", "null"]
    },
    "fallback_image_url": {
      "type": ["array", "null"],
      "items": {
        "type": ["string", "null"]
      }
    },
    "feed_count": {
      "type": ["integer", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "is_catalog_segment": {
      "type": ["boolean", "null"]
    },
    "name": {
      "type": ["string", "null"]
    },
    "product_count": {
      "type": ["integer", "null"]
    },
    "vertical": {
      "type": ["string", "null"]
    }
  }
}
"""
