"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/profilepicturesource.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/profilepicturesource.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "bottom": {
      "type": ["integer", "null"]
    },
    "cache_key": {
      "type": ["string", "null"]
    },
    "height": {
      "type": ["integer", "null"]
    },
    "is_silhouette": {
      "type": ["boolean", "null"]
    },
    "left": {
      "type": ["integer", "null"]
    },
    "right": {
      "type": ["integer", "null"]
    },
    "top": {
      "type": ["integer", "null"]
    },
    "url": {
      "type": ["string", "null"]
    },
    "width": {
      "type": ["integer", "null"]
    }
  }
}
"""
