"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/profile.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/profile.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "can_post": {
      "type": ["boolean", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "link": {
      "type": ["string", "null"]
    },
    "name": {
      "type": ["string", "null"]
    },
    "pic": {
      "type": ["string", "null"]
    },
    "pic_large": {
      "type": ["string", "null"]
    },
    "pic_small": {
      "type": ["string", "null"]
    },
    "pic_square": {
      "type": ["string", "null"]
    },
    "profile_type": {
      "type": ["string", "null"]
    },
    "username": {
      "type": ["string", "null"]
    }
  }
}
"""
