"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/recommendation.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/recommendation.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "created_time": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "has_rating": {
      "type": ["boolean", "null"]
    },
    "has_review": {
      "type": ["boolean", "null"]
    },
    "open_graph_story": {
      "type": ["string", "null"]
    },
    "rating": {
      "type": ["integer", "null"]
    },
    "recommendation_type": {
      "type": ["string", "null"]
    },
    "review_text": {
      "type": ["string", "null"]
    }
  }
}
"""
