"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/rtbdynamicpost.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/rtbdynamicpost.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "created": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "description": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "image_url": {
      "type": ["string", "null"]
    },
    "link": {
      "type": ["string", "null"]
    },
    "message": {
      "type": ["string", "null"]
    },
    "owner_id": {
      "type": ["string", "null"]
    },
    "place_id": {
      "type": ["string", "null"]
    },
    "product_id": {
      "type": ["string", "null"]
    },
    "title": {
      "type": ["string", "null"]
    }
  }
}
"""
