"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/url.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/url.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "engagement": {
      "type": ["string", "null"]
    },
    "id": {
      "type": ["string", "null"]
    },
    "og_object": {
      "type": ["string", "null"]
    },
    "ownership_permissions": {
      "type": ["string", "null"]
    },
    "scopes": {
      "type": ["string", "null"]
    }
  }
}
"""
