"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/videocopyrightrule.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/videocopyrightrule.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "copyrights": {
      "type": ["array", "null"],
      "items": {
        "type": ["string", "null"]
      }
    },
    "created_date": {
      "type": ["string", "null"],
      "format": "date-time"
    },
    "id": {
      "type": ["string", "null"]
    },
    "is_in_migration": {
      "type": ["boolean", "null"]
    },
    "name": {
      "type": ["string", "null"]
    }
  }
}
"""
