"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/voipinfo.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/shared/voipinfo.json'

CONTENT = """\
{
  "type": ["object", "null"],
  "properties": {
    "has_mobile_app": {
      "type": ["boolean", "null"]
    },
    "has_permission": {
      "type": ["boolean", "null"]
    },
    "is_callable": {
      "type": ["boolean", "null"]
    },
    "is_callable_webrtc": {
      "type": ["boolean", "null"]
    },
    "is_pushable": {
      "type": ["boolean", "null"]
    },
    "reason_code": {
      "type": ["integer", "null"]
    },
    "reason_description": {
      "type": ["string", "null"]
    }
  }
}
"""
