"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/page.json (part 2 of 2) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/page.json'
PART = 2
TOTAL_PARTS = 2

CONTENT = """\
          "type": ["array", "null"],
          "items": {
            "$ref": "rtbdynamicpost.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "scheduled_posts": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "pagepost.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "secondary_receivers": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "application.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "pagesettings.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "shop_setup_status": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "commercemerchantsettingssetupstatus.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "subscribed_apps": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "application.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "tabs": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "tab.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "tagged": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "pagepost.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "thread_owner": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "pagethreadowner.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "threads": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "unifiedthread.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "video_copyright_rules": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "videocopyrightrule.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "video_lists": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "videolist.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "videos": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "advideo.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "visitor_posts": {
      "type": ["object", "null"],
      "properties": {
        "data": {
          "type": ["array", "null"],
          "items": {
            "$ref": "pagepost.json"
          }
        },
        "paging": {
          "type": ["object", "null"],
          "properties": {
            "previous": {
              "type": ["string", "null"]
            },
            "next": {
              "type": ["string", "null"]
            },
            "cursors": {
              "type": "object",
              "properties": {
                "before": {
                  "type": ["string", "null"]
                },
                "after": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    }
  }
}
"""
