"""Searchable copy of airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/post_insights.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-pages/source_facebook_pages/schemas/post_insights.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": ["null", "object"],
  "properties": {
    "name": {
      "type": ["null", "string"]
    },
    "period": {
      "type": ["null", "string"]
    },
    "values": {
      "type": ["null", "array"],
      "items": {
        "type": ["null", "object"],
        "properties": {
          "value": {
            "type": ["null", "object", "string", "integer"]
          },
          "end_time": {
            "type": ["null", "string"],
            "format": "date-time"
          }
        }
      }
    },
    "title": {
      "type": ["null", "string"]
    },
    "description": {
      "type": ["null", "string"]
    },
    "id": {
      "type": ["null", "string"]
    }
  }
}
"""
