"""Searchable copy of airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml (part 2 of 8) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml'
PART = 2
TOTAL_PARTS = 8

CONTENT = """\
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_COMPANY_SIZE"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_company_size_analytics"
    ad_member_country_analytics:
      type: DeclarativeStream
      name: ad_member_country_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_country_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_COUNTRY_V2)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_COUNTRY_V2"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_country_analytics"
    ad_member_job_function_analytics:
      type: DeclarativeStream
      name: ad_member_job_function_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_job_function_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_JOB_FUNCTION)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_JOB_FUNCTION"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_job_function_analytics"
    ad_member_job_title_analytics:
      type: DeclarativeStream
      name: ad_member_job_title_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_job_title_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_JOB_TITLE)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_JOB_TITLE"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_job_title_analytics"
    ad_member_industry_analytics:
      type: DeclarativeStream
      name: ad_member_industry_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_industry_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_INDUSTRY)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_INDUSTRY"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_industry_analytics"
    ad_member_seniority_analytics:
      type: DeclarativeStream
      name: ad_member_seniority_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_seniority_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_SENIORITY)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_SENIORITY"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_seniority_analytics"
    ad_member_region_analytics:
      type: DeclarativeStream
      name: ad_member_region_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_region_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_REGION_V2)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_REGION_V2"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_region_analytics"
    ad_member_company_analytics:
      type: DeclarativeStream
      name: ad_member_company_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_company_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_COMPANY)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "MEMBER_COMPANY"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_member_company_analytics"
    custom_analytics_report:
      type: DeclarativeStream
      name: custom_analytics_report
      primary_key:
        - string_of_pivot_values
        - end_date
        - sponsoredCampaign
      retriever:
        type: SimpleRetriever
        $parameters:
          name: custom_analytics_report
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "DYNAMIC_FIELD"
            timeGranularity: "DYNAMIC_FIELD"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            $ref: "#/definitions/custom_report_request_headers"
          error_handler:
            $ref: "#/definitions/custom_report_error_handler"
        record_selector:
          $ref: "#/definitions/custom_report_record_selector"
        paginator:
          $ref: "#/definitions/custom_report_paginator"
        partition_router:
          $ref: "#/definitions/custom_report_partition_router"
      incremental_sync:
        $ref: "#/definitions/custom_report_incremental_sync"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "DYNAMIC_FIELD"
              value_type: string
      schema_loader:
        $ref: "#/definitions/custom_report_schema_loader"
    custom_statistics_report:
      type: DeclarativeStream
      name: custom_statistics_report
      primary_key:
        - string_of_pivot_values
        - end_date
        - sponsoredCampaign
      retriever:
        type: SimpleRetriever
        $parameters:
          name: custom_statistics_report
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: statistics
            pivots: "DYNAMIC_FIELD"
            timeGranularity: "DYNAMIC_FIELD"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            $ref: "#/definitions/custom_report_request_headers"
          error_handler:
            $ref: "#/definitions/custom_report_error_handler"
        record_selector:
          $ref: "#/definitions/custom_report_record_selector"
        paginator:
          $ref: "#/definitions/custom_report_paginator"
        partition_router:
          $ref: "#/definitions/custom_report_partition_router"
      incremental_sync:
        $ref: "#/definitions/custom_report_incremental_sync"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "DYNAMIC_FIELD"
              value_type: string
      schema_loader:
        $ref: "#/definitions/custom_report_schema_loader"
  custom_report_request_headers:
    Linkedin-Version: "202601"
    X-Restli-Protocol-Version: 2.0.0
  custom_report_error_handler:
    type: CustomErrorHandler
    class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
    max_retries: 5
    max_time: 1800
    backoff_strategies:
      - type: CustomBackoffStrategy
        class_name: source_declarative_manifest.components.LinkedInAdsDataVolumeBackoffStrategy
      - type: ExponentialBackoffStrategy
        factor: 5
  custom_report_record_selector:
    type: RecordSelector
    extractor:
      type: CustomRecordExtractor
      class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
    schema_normalization: Default
  custom_report_paginator:
    type: NoPagination
  custom_report_partition_router:
    type: SubstreamPartitionRouter
    parent_stream_configs:
      - type: ParentStreamConfig
        parent_key: id
        partition_field: campaign_id
        stream:
          $ref: "#/definitions/streams/campaigns"
  custom_report_incremental_sync:
    type: DatetimeBasedCursor
    cursor_field: end_date
    cursor_datetime_formats:
      - "%Y-%m-%d"
    datetime_format: "%Y-%m-%d"
    cursor_granularity: P0D
    step: P30D
    lookback_window: P{{ config.get('lookback_window', 0) }}D
    start_datetime:
      type: MinMaxDatetime
      datetime: "{{ config['start_date'] }}"
      datetime_format: "%Y-%m-%d"
  custom_report_schema_loader:
    type: InlineSchemaLoader
    schema:
      $ref: "#/schemas/ad_campaign_analytics"
  base_requester:
    type: HttpRequester
    url_base: https://api.linkedin.com/rest/
    authenticator: "#/definitions/authenticator"
  # Authenticators
  bearer_authenticator:
    type: BearerAuthenticator
    api_token: "{{ config['credentials']['access_token'] }}"
  oauth_authenticator:
    type: OAuthAuthenticator
    refresh_request_body: {}
    token_refresh_endpoint: https://www.linkedin.com/oauth/v2/accessToken
    grant_type: refresh_token
    client_id: '{{ config["credentials"]["client_id"] }}'
    client_secret: '{{ config["credentials"]["client_secret"] }}'
    refresh_token: '{{ config["credentials"]["refresh_token"] }}'
  authenticator:
    type: SelectiveAuthenticator
    authenticator_selection_path: ["credentials", "auth_method"]
    authenticators:
      oAuth2.0: "#/definitions/oauth_authenticator"
      access_token: "#/definitions/bearer_authenticator"

  # Analytics streams require including which properties to query for in the API request. They also only allow
  # for a maximum of 20 fields per request, so we use PropertyChunking to make multiple requests to assemble
  # the entire record
  analytics_query_properties:
    type: QueryProperties
    property_list: &analytics_query_property_list
      - actionClicks
      - adUnitClicks
      - approximateMemberReach
      - cardClicks
      - cardImpressions
      - clicks
      - commentLikes
      - comments
      - companyPageClicks
      - conversionValueInLocalCurrency
      - costInLocalCurrency
      - costInUsd
      - dateRange
      - documentCompletions
      - documentFirstQuartileCompletions
      - documentMidpointCompletions
      - documentThirdQuartileCompletions
      - downloadClicks
      - externalWebsiteConversions
      - externalWebsitePostClickConversions
      - externalWebsitePostViewConversions
      - follows
      - fullScreenPlays
      - impressions
      - jobApplications
      - jobApplyClicks
      - landingPageClicks
      - leadGenerationMailContactInfoShares
      - leadGenerationMailInterestedClicks
      - likes
      - oneClickLeadFormOpens
      - oneClickLeads
      - opens
      - otherEngagements
      - pivotValues
      - postClickJobApplications
      - postClickJobApplyClicks
      - postClickRegistrations
      - postViewJobApplications
      - postViewJobApplyClicks
      - postViewRegistrations
      - reactions
      - registrations
      - sends
      - shares
      - talentLeads
      - textUrlClicks
      - totalEngagements
      - validWorkEmailLeads
      - videoCompletions
      - videoFirstQuartileCompletions
      - videoMidpointCompletions
      - videoStarts
      - videoThirdQuartileCompletions
      - videoViews
      - viralCardClicks
      - viralCardImpressions
      - viralClicks
      - viralCommentLikes
      - viralComments
      - viralCompanyPageClicks
      - viralDocumentCompletions
      - viralDocumentFirstQuartileCompletions
      - viralDocumentMidpointCompletions
      - viralDocumentThirdQuartileCompletions
      - viralDownloadClicks
      - viralExternalWebsiteConversions
      - viralExternalWebsitePostClickConversions
      - viralExternalWebsitePostViewConversions
      - viralFollows
      - viralFullScreenPlays
      - viralImpressions
      - viralJobApplications
      - viralJobApplyClicks
      - viralLandingPageClicks
      - viralLikes
      - viralOneClickLeadFormOpens
      - viralOneClickLeads
      - viralOtherEngagements
      - viralPostClickJobApplications
      - viralPostClickJobApplyClicks
      - viralPostClickRegistrations
      - viralPostViewJobApplications
      - viralPostViewJobApplyClicks
      - viralPostViewRegistrations
      - viralReactions
      - viralRegistrations
      - viralShares
      - viralTotalEngagements
      - viralVideoCompletions
      - viralVideoFirstQuartileCompletions
      - viralVideoMidpointCompletions
      - viralVideoStarts
      - viralVideoThirdQuartileCompletions
      - viralVideoViews
    # dateRange and pivotValue fields are used to merge records back together so they must be in every API request
    always_include_properties:
      - dateRange
      - pivotValues
    property_chunking:
      type: PropertyChunking
      property_limit_type: property_count
      property_limit: 18
      record_merge_strategy:
        type: GroupByKeyMergeStrategy
        key: ["end_date", "string_of_pivot_values"]
    property_selector:
      type: JsonSchemaPropertySelector
  impression_device_analytics_query_properties:
    type: QueryProperties
    property_list: *analytics_query_property_list
    always_include_properties:
      - dateRange
      - pivotValues
    property_chunking:
      type: PropertyChunking
      property_limit_type: property_count
      property_limit: 18
      record_merge_strategy:
        type: GroupByKeyMergeStrategy
        key: ["end_date", "string_of_pivot_values", "sponsoredCampaign"]
    property_selector:
      type: JsonSchemaPropertySelector

streams:
  - $ref: "#/definitions/streams/accounts"
  - $ref: "#/definitions/streams/organizations"
  - $ref: "#/definitions/streams/account_users"
  - $ref: "#/definitions/streams/campaigns"
  - $ref: "#/definitions/streams/campaign_groups"
  - $ref: "#/definitions/streams/creatives"
  - $ref: "#/definitions/streams/conversions"
  - $ref: "#/definitions/streams/lead_forms"
  - $ref: "#/definitions/streams/lead_form_responses"
  - $ref: "#/definitions/streams/videos"
  - $ref: "#/definitions/streams/ad_member_seniority_analytics"
  - $ref: "#/definitions/streams/ad_campaign_analytics"
  - $ref: "#/definitions/streams/ad_creative_analytics"
  - $ref: "#/definitions/streams/ad_impression_device_analytics"
  - $ref: "#/definitions/streams/ad_member_company_size_analytics"
  - $ref: "#/definitions/streams/ad_member_country_analytics"
  - $ref: "#/definitions/streams/ad_member_job_function_analytics"
  - $ref: "#/definitions/streams/ad_member_job_title_analytics"
  - $ref: "#/definitions/streams/ad_member_industry_analytics"
  - $ref: "#/definitions/streams/ad_member_region_analytics"
  - $ref: "#/definitions/streams/ad_member_company_analytics"

dynamic_streams:
  - type: DynamicDeclarativeStream
    stream_template:
      $ref: "#/definitions/streams/custom_analytics_report"
    components_resolver:
      type: ConfigComponentsResolver
      stream_config:
        type: StreamConfig
        configs_pointer:
          - ad_analytics_reports
      components_mapping:
        - type: ComponentMappingDefinition
          field_path: ["name"]
          value: "custom_{{components_values['name']}}"
        - type: ComponentMappingDefinition
          field_path: ["retriever", "requester", "request_parameters", "pivot"]
          value: "(value:{{components_values['pivot_by']}})"
        - type: ComponentMappingDefinition
          field_path:
            ["retriever", "requester", "request_parameters", "timeGranularity"]
          value: "(value:{{components_values['time_granularity']}})"
        - type: ComponentMappingDefinition
          field_path:
            ["transformations","1","fields","0","value"]
          value: "{{components_values['pivot_by']}}"
  - type: DynamicDeclarativeStream
    stream_template:
      $ref: "#/definitions/streams/custom_statistics_report"
    components_resolver:
      type: ConfigComponentsResolver
      stream_config:
        type: StreamConfig
        configs_pointer:
          - ad_statistics_reports
      components_mapping:
        - type: ComponentMappingDefinition
          field_path: ["name"]
          value: "custom_statistics_{{components_values['name']}}"
        - type: ComponentMappingDefinition
          field_path: ["retriever", "requester", "request_parameters", "pivots"]
          value: "List({{ ','.join(components_values['pivots']) }})"
        - type: ComponentMappingDefinition
          field_path:
            ["retriever", "requester", "request_parameters", "timeGranularity"]
          value: "(value:{{components_values['time_granularity']}})"
        - type: ComponentMappingDefinition
          field_path:
            ["transformations","1","fields","0","value"]
          value: "{{ ','.join(components_values['pivots']) }}"

# LinkedIn Ads does not publish their standard API rate limits.
# https://learn.microsoft.com/en-us/linkedin/shared/api-guide/concepts/rate-limits
# I looked into our test account to establish some baselines, but it seems like each endpoint
# has its own individually tracked rate limit that resets daily. There are also tiers, but
# there is not a good way of ascertaining what value are for each.
#
# It is likely that certain customers may have a greater limit provisioned so allow for a max of 50.
#
# Our OAuth app supports 15,000,000 req/day for /adAnalytics endpoints
#
# Update 2025-06-16: Added num_workers to the config to allow for more control over the number
# of workers and set the default to 3. This is because some customers were experiencing rate
# limiting issues with v5.5.0 of the connector -- migration to manifest-only.
concurrency_level:
  type: ConcurrencyLevel
  default_concurrency: "{{ config.get('num_workers', 6) }}"
  max_concurrency: 50

api_budget:
  type: HTTPAPIBudget
  policies:
    - type: MovingWindowCallRatePolicy
      rates:
        # As mentioned, there are no published rate limits, setting an initial max of 5 req per 10 seconds.
        # We can adjust this as needed.
        - limit: 6
          interval: PT10S
      matchers:
        - method: GET
          url_path_pattern: "adAnalytics"
  status_codes_for_ratelimit_hit:
    - 429

spec:
  type: Spec
  connection_specification:
    $schema: http://json-schema.org/draft-07/schema#
    title: "Linkedin Ads Spec"
    type: object
    required:
      - start_date
    additionalProperties: true
    properties:
      credentials:
        title: Authentication
        type: object
        oneOf:
          - type: object
            title: OAuth2.0
            required:
              - client_id
              - client_secret
              - refresh_token
            properties:
              auth_method:
                type: string
                const: oAuth2.0
              client_id:
                type: string
                title: Client ID
                description: "The client ID of your developer application. Refer to our <a href='https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide'>documentation</a> for more information."
                airbyte_secret: true
              client_secret:
                type: string
                title: Client Secret
                description: "The client secret of your developer application. Refer to our <a href='https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide'>documentation</a> for more information."
                airbyte_secret: true
              refresh_token:
                type: string
                title: Refresh Token
                description: "The key to refresh the expired access token. Refer to our <a href='https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide'>documentation</a> for more information."
                airbyte_secret: true
          - title: Access Token
            type: object
            required:
              - access_token
            properties:
              auth_method:
                type: string
                const: access_token
              access_token:
                type: string
                title: Access Token
                description: "The access token generated for your developer application. Refer to our <a href='https://docs.airbyte.com/integrations/sources/linkedin-ads#setup-guide'>documentation</a> for more information."
                airbyte_secret: true
      start_date:
        type: string
        title: Start Date
        pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
        pattern_descriptor: YYYY-MM-DD
"""
