"""Searchable copy of airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml (part 1 of 8) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml'
PART = 1
TOTAL_PARTS = 8

CONTENT = """\
version: 4.1.0

type: DeclarativeSource

check:
  type: CheckStream
  stream_names:
    - accounts

definitions:
  ad_analytics_error_handler:
    type: CustomErrorHandler
    class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
    max_retries: 5
    max_time: 1800
    backoff_strategies:
      - type: CustomBackoffStrategy
        class_name: source_declarative_manifest.components.LinkedInAdsDataVolumeBackoffStrategy
      - type: ExponentialBackoffStrategy
        factor: 5
  streams:
    accounts:
      type: DeclarativeStream
      name: accounts
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: adAccounts
          http_method: GET
          request_parameters:
            q: search
          request_headers:
            Linkedin-Version: "202601"
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          record_filter:
            condition: "{{ record['id'] in config['account_ids'] if config.get('account_ids') else True }}"
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageToken
          page_size_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageSize
          pagination_strategy:
            type: CursorPagination
            page_size: 500
            cursor_value: '{{ response.get("metadata", {}).get("nextPageToken", {}) }}'
            stop_condition: '{{ not response.get("metadata", {}).get("nextPageToken", {}) }}'
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/accounts"
    organizations:
      type: DeclarativeStream
      name: organizations
      primary_key:
        - organization
        - role
        - roleAssignee
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: organizationAcls
          http_method: GET
          request_parameters:
            q: roleAssignee
            # organizationAcls is a Rest.li finder paged with start/count (it does not
            # support pageToken); count must match the OffsetIncrement page_size below.
            count: "500"
          request_headers:
            Linkedin-Version: "202601"
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: start
          pagination_strategy:
            type: OffsetIncrement
            page_size: 500
      transformations:
        - type: AddFields
          fields:
            # LinkedIn docs show the organization URN as `organization` in some
            # organizationAcls samples and `organizationTarget` in others; normalize
            # to `organization` so the primary key is never null.
            - path:
                - organization
              value: "{{ record.get('organization') or record.get('organizationTarget') }}"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/organizations"
    account_users:
      type: DeclarativeStream
      name: account_users
      primary_key:
        - account
        - user
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: adAccountUsers
          http_method: GET
          request_parameters:
            q: accounts
            count: "500"
            accounts: "urn:li:sponsoredAccount:{{ stream_slice.get('account_id') }}"
          request_headers:
            Linkedin-Version: "202601"
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: start
          pagination_strategy:
            type: OffsetIncrement
            page_size: 500
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: lastModified
        is_client_side_incremental: true
        cursor_datetime_formats:
          - "%ms"
          - "%Y-%m-%dT%H:%M:%S%z"
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ format_datetime(config['start_date'], '%Y-%m-%dT%H:%M:%S%z') }}"
          datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/account_users"
    campaigns:
      type: DeclarativeStream
      name: campaigns
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAccounts/{{stream_slice.get('account_id')}}/adCampaigns
          http_method: GET
          request_parameters:
            q: search
            search: "(status:(values:List(ACTIVE,PAUSED,ARCHIVED,COMPLETED,CANCELED,DRAFT,PENDING_DELETION,REMOVED)))"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageToken
          page_size_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageSize
          pagination_strategy:
            type: CursorPagination
            page_size: 500
            cursor_value: '{{ response.get("metadata", {}).get("nextPageToken", {}) }}'
            stop_condition: '{{ not response.get("metadata", {}).get("nextPageToken", {}) }}'
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: lastModified
        is_client_side_incremental: true
        cursor_datetime_formats:
          - "%ms"
          - "%Y-%m-%dT%H:%M:%S%z"
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ format_datetime(config['start_date'], '%Y-%m-%dT%H:%M:%S%z') }}"
          datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/campaigns"
    campaign_groups:
      type: DeclarativeStream
      name: campaign_groups
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAccounts/{{stream_slice.get('account_id')}}/adCampaignGroups
          http_method: GET
          request_parameters:
            q: search
            search: "(status:(values:List(ACTIVE,ARCHIVED,CANCELED,DRAFT,PAUSED,PENDING_DELETION,REMOVED)))"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageToken
          page_size_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageSize
          pagination_strategy:
            type: CursorPagination
            page_size: 500
            cursor_value: '{{ response.get("metadata", {}).get("nextPageToken", {}) }}'
            stop_condition: '{{ not response.get("metadata", {}).get("nextPageToken", {}) }}'
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: lastModified
        is_client_side_incremental: true
        cursor_datetime_formats:
          - "%ms"
          - "%Y-%m-%dT%H:%M:%S%z"
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ format_datetime(config['start_date'], '%Y-%m-%dT%H:%M:%S%z') }}"
          datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/campaign_groups"
    creatives:
      type: DeclarativeStream
      name: creatives
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: adAccounts/{{stream_slice.get('account_id')}}/creatives
          http_method: GET
          request_parameters:
            q: criteria
          request_headers:
            Linkedin-Version: "202601"
            X-RestLi-Method: FINDER
          error_handler:
            type: CompositeErrorHandler
            error_handlers:
              - type: DefaultErrorHandler
                response_filters:
                  - type: HttpResponseFilter
                    action: RATE_LIMITED
                    http_codes:
                      - 429
                    error_message: Rate limit exceeded for LinkedIn API.
                  - type: HttpResponseFilter
                    action: RETRY
                    http_codes:
                      - 500
                      - 503
              - type: CustomErrorHandler
                class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
                backoff_strategies:
                  - type: ExponentialBackoffStrategy
                    factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageToken
          page_size_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: pageSize
          pagination_strategy:
            type: CursorPagination
            page_size: 100
            cursor_value: '{{ response.get("metadata", {}).get("nextPageToken", {}) }}'
            stop_condition: '{{ not response.get("metadata", {}).get("nextPageToken", {}) }}'
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: lastModifiedAt
        is_client_side_incremental: true
        cursor_datetime_formats:
          - "%ms"
          - "%Y-%m-%dT%H:%M:%S%z"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ format_datetime(config['start_date'], '%Y-%m-%dT%H:%M:%S%z') }}"
          datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/creatives"
    conversions:
      type: DeclarativeStream
      name: conversions
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: conversions
          http_method: GET
          request_parameters:
            q: account
            account: urn:li:sponsoredAccount:{{stream_slice.get('account_id')}}
            count: "500"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path:
              - elements
          schema_normalization: Default
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: start
          pagination_strategy:
            type: OffsetIncrement
            page_size: 500
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: lastModified
        is_client_side_incremental: true
        cursor_datetime_formats:
          - "%ms"
        datetime_format: "%Y-%m-%dT%H:%M:%S%z"
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ format_datetime(config['start_date'], '%Y-%m-%dT%H:%M:%S%z') }}"
          datetime_format: "%Y-%m-%dT%H:%M:%S%z"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/conversions"
    lead_forms:
      type: DeclarativeStream
      name: lead_forms
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: leadForms?owner=(sponsoredAccount:urn%3Ali%3AsponsoredAccount%3A{{stream_slice.get('account_id')}})
          http_method: GET
          request_parameters:
            q: owner
            count: "500"
          request_headers:
            LinkedIn-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path:
              - elements
          schema_normalization: Default
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: start
          pagination_strategy:
            type: CursorPagination
            cursor_value: "{{ response.get('paging', {}).get('start', 0) + response.get('paging', {}).get('count', 0) }}"
            stop_condition: "{{ response.get('paging', {}).get('total', 0) == 0 }}"
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/lead_forms"
    lead_form_responses:
      type: DeclarativeStream
      name: lead_form_responses
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: /leadFormResponses?owner=(sponsoredAccount:urn%3Ali%3AsponsoredAccount%3A{{stream_slice.get('account_id')}})&leadType=(leadType:SPONSORED)
          http_method: GET
          request_parameters:
            q: owner
            count: "500"
          request_headers:
            LinkedIn-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path:
              - elements
          schema_normalization: Default
        paginator:
          type: DefaultPaginator
          page_token_option:
            type: RequestOption
            inject_into: request_parameter
            field_name: start
          pagination_strategy:
            type: CursorPagination
            cursor_value: "{{ response.get('paging', {}).get('start', 0) + response.get('paging', {}).get('count', 0) }}"
            stop_condition: "{{ response.get('paging', {}).get('total', 0) == 0 }}"
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: account_id
              stream:
                $ref: "#/definitions/streams/accounts"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/lead_form_responses"
    # Internal parent stream for `videos`; not exposed in the `streams` list.
    # Resolves each creative's sponsored-content reference (urn:li:share / urn:li:ugcPost)
    # to the underlying post, and keeps only the posts whose media is a video.
    # Creatives without a `content.reference` (e.g. text ads) produce no partition.
    videos_creative_posts:
      type: DeclarativeStream
      name: videos_creative_posts
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: posts/{{ stream_slice.get('post_urn') | replace(':', '%3A') }}
          http_method: GET
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            response_filters:
              # A creative can reference a post that was deleted (404) or that the
              # authenticated user is not allowed to read (403, e.g. missing
              # r_organization_social when authenticating with a raw access token).
              # Skip those posts rather than failing the whole videos sync.
              - type: HttpResponseFilter
                http_codes:
                  - 403
                  - 404
                action: IGNORE
                error_message: "Skipping a creative's post that is deleted or not readable by the authenticated user; the videos it references will not be synced."
              # A creative's `content.reference` can also be an urn:li:adInMailContent
              # (Message Ads), which is not a post URN - the Posts API rejects it with
              # 400 INVALID_URN_TYPE - and an explicitly null reference would produce a
              # request for `posts/None`, also rejected as a malformed URN. Skip both:
              # neither can reference a video. The predicate only matches 400s whose
              # message points at the URN, so genuine request errors still fail loudly.
              - type: HttpResponseFilter
                predicate: "{{ response.get('status') == 400 and 'URN' in ((response.get('message') or '') | upper) }}"
                action: IGNORE
                error_message: "Skipping a creative reference that is not a fetchable post URN (e.g. urn:li:adInMailContent from Message Ads); it cannot reference a video."
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path: []
          record_filter:
            type: RecordFilter
            # Keep only video posts. Image posts (urn:li:image) and legacy assets
            # uploaded through the deprecated Assets API (urn:li:digitalmediaAsset)
            # are not retrievable through the Videos API.
            condition: "{{ 'urn:li:video:' in (((record.get('content') or {}).get('media') or {}).get('id') or '') }}"
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: content/reference
              partition_field: post_urn
              stream:
                $ref: "#/definitions/streams/creatives"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $schema: http://json-schema.org/draft-07/schema#
          type:
            - "null"
            - object
          additionalProperties: true
          properties:
            id:
              type:
                - "null"
                - string
            content:
              type:
                - "null"
                - object
    # Fetches each ad video individually (GET /rest/videos/{videoUrn}). The Videos API
    # also exposes a `q=associatedAccount` finder listing an account's whole media
    # library in one call, but LinkedIn gates that finder at the application level:
    # a token holding r_ads - the permission the API docs list for this API - still
    # receives 403 ACCESS_DENIED ("Not enough permissions to access:
    # partnerApiVideosExternal.FINDER-associatedAccount.<version>") unless LinkedIn has
    # granted the application access. GET by URN works with plain r_ads, so the stream
    # resolves the videos actually referenced by the account's creatives instead.
    videos:
      type: DeclarativeStream
      name: videos
      primary_key:
        - id
      retriever:
        type: SimpleRetriever
        requester:
          $ref: "#/definitions/base_requester"
          path: videos/{{ stream_slice.get('video_urn') | replace(':', '%3A') }}
          http_method: GET
          # The same video is fetched once per referencing post; the HTTP cache collapses
          # those duplicate GETs into one API call (a record is still emitted per reference).
          use_cache: true
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            type: CustomErrorHandler
            class_name: source_declarative_manifest.components.LinkedInAdsErrorHandler
            response_filters:
              # The video may have been deleted since the post was published (404), or
              # belong to an organization the authenticated user cannot read (403).
              - type: HttpResponseFilter
                http_codes:
                  - 403
                  - 404
                action: IGNORE
                error_message: "Skipping a video that is deleted or not readable by the authenticated user."
            backoff_strategies:
              - type: ExponentialBackoffStrategy
                factor: 5
        record_selector:
          type: RecordSelector
          extractor:
            type: DpathExtractor
            field_path: []
          schema_normalization: Default
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: content/media/id
              partition_field: video_urn
              stream:
                $ref: "#/definitions/streams/videos_creative_posts"
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/videos"
    ad_campaign_analytics:
      type: DeclarativeStream
      name: ad_campaign_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
        - sponsoredCampaign
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_campaign_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:CAMPAIGN)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id', []) | join(',urn%3Ali%3AsponsoredCampaign%3A') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: GroupingPartitionRouter
          group_size: 50
          underlying_partition_router:
            type: SubstreamPartitionRouter
            parent_stream_configs:
              - type: ParentStreamConfig
                parent_key: id
                partition_field: campaign_id
                stream:
                  $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        global_substream_cursor: true
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ record.get('pivotValues', [''])[0].split(':')[-1] }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "CAMPAIGN"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_campaign_analytics"
    ad_creative_analytics:
      type: DeclarativeStream
      name: ad_creative_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_creative_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:CREATIVE)"
            timeGranularity: "(value:DAILY)"
            creatives: "List({{ stream_partition.get('creative_id', []) | map('replace', ':', '%3A') | join(',') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: GroupingPartitionRouter
          group_size: 50
          underlying_partition_router:
            type: SubstreamPartitionRouter
            parent_stream_configs:
              - type: ParentStreamConfig
                parent_key: id
                partition_field: creative_id
                stream:
                  $ref: "#/definitions/streams/creatives"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        global_substream_cursor: true
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCreative
              value: "{{ record.get('pivotValues', [''])[0].split(':')[-1] }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "CREATIVE"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_creative_analytics"
    ad_impression_device_analytics:
      type: DeclarativeStream
      name: ad_impression_device_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
        - sponsoredCampaign
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_impression_device_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: statistics
            pivots: "List(CAMPAIGN,IMPRESSION_DEVICE_TYPE)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id', []) | join(',urn%3Ali%3AsponsoredCampaign%3A') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/impression_device_analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
            transform_campaign_statistics_pivots: true
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: GroupingPartitionRouter
          group_size: 50
          underlying_partition_router:
            type: SubstreamPartitionRouter
            parent_stream_configs:
              - type: ParentStreamConfig
                parent_key: id
                partition_field: campaign_id
                stream:
                  $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        global_substream_cursor: true
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ record.get('sponsoredCampaign') }}"
              value_type: string
        - type: AddFields
          fields:
            - path:
                - pivot
              value: "IMPRESSION_DEVICE_TYPE"
              value_type: string
      schema_loader:
        type: InlineSchemaLoader
        schema:
          $ref: "#/schemas/ad_impression_device_analytics"
    ad_member_company_size_analytics:
      type: DeclarativeStream
      name: ad_member_company_size_analytics
      primary_key:
        - string_of_pivot_values
        - end_date
      retriever:
        type: SimpleRetriever
        $parameters:
          name: ad_member_company_size_analytics
        requester:
          type: CustomRequester
          class_name: source_declarative_manifest.components.SafeEncodeHttpRequester
          url_base: https://api.linkedin.com/rest/
          authenticator: "#/definitions/authenticator"
          path: adAnalytics
          http_method: GET
          request_parameters:
            q: analytics
            pivot: "(value:MEMBER_COMPANY_SIZE)"
            timeGranularity: "(value:DAILY)"
            campaigns: "List(urn%3Ali%3AsponsoredCampaign%3A{{ stream_partition.get('campaign_id') }})"
            dateRange: "(start:(year:{{ str_to_datetime(stream_interval.get('start_time')).year }},month:{{ str_to_datetime(stream_interval.get('start_time')).month }},day:{{ str_to_datetime(stream_interval.get('start_time')).day }}),end:(year:{{ str_to_datetime(stream_interval.get('end_time')).year }},month:{{ str_to_datetime(stream_interval.get('end_time')).month }},day:{{ str_to_datetime(stream_interval.get('end_time')).day }}))"
            fields: "#/definitions/analytics_query_properties"
          request_headers:
            Linkedin-Version: "202601"
            X-Restli-Protocol-Version: 2.0.0
          error_handler:
            $ref: "#/definitions/ad_analytics_error_handler"
        record_selector:
          type: RecordSelector
          extractor:
            type: CustomRecordExtractor
            class_name: source_declarative_manifest.components.LinkedInAdsRecordExtractor
          schema_normalization: Default
        paginator:
          type: NoPagination
        partition_router:
          type: SubstreamPartitionRouter
          parent_stream_configs:
            - type: ParentStreamConfig
              parent_key: id
              partition_field: campaign_id
              stream:
                $ref: "#/definitions/streams/campaigns"
      incremental_sync:
        type: DatetimeBasedCursor
        cursor_field: end_date
        cursor_datetime_formats:
          - "%Y-%m-%d"
        datetime_format: "%Y-%m-%d"
        cursor_granularity: P0D
        step: P30D
        lookback_window: P{{ config.get('lookback_window', 0) }}D
        start_datetime:
          type: MinMaxDatetime
          datetime: "{{ config['start_date'] }}"
          datetime_format: "%Y-%m-%d"
      transformations:
        - type: AddFields
          fields:
            - path:
                - sponsoredCampaign
              value: "{{ stream_partition.get('campaign_id') }}"
"""
