"""Searchable copy of airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml (part 3 of 8) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml'
PART = 3
TOTAL_PARTS = 8

CONTENT = """\
        description: "UTC date in the format YYYY-MM-DD. Any data before this date will not be replicated."
        examples:
          - "2021-05-17"
        format: date
      lookback_window:
        type: integer
        title: Lookback Window
        default: 0
        minimum: 0
        description: How far into the past to look for records. (in days)
      account_ids:
        title: Account IDs
        type: array
        description: 'Specify the account IDs to pull data from, separated by a space. Leave this field empty if you want to pull the data from all accounts accessible by the authenticated user. See the <a href="https://www.linkedin.com/help/linkedin/answer/a424270/find-linkedin-ads-account-details?lang=en">LinkedIn docs</a> to locate these IDs.'
        items:
          type: integer
        examples:
          - 123456789
        default: []
      ad_analytics_reports:
        title: Custom Ad Analytics Reports
        type: array
        items:
          type: object
          title: Ad Analytics Report Configuration
          description: "Config for custom ad Analytics Report"
          required:
            - name
            - pivot_by
            - time_granularity
          properties:
            name:
              title: Report Name
              description: "The name for the custom report."
              type: string
            pivot_by:
              title: Pivot Category
              description: "Choose a category to pivot your analytics report around. This selection will organize your data based on the chosen attribute, allowing you to analyze trends and performance from different perspectives."
              type: string
              enum:
                - COMPANY
                - ACCOUNT
                - SHARE
                - CAMPAIGN
                - CREATIVE
                - CAMPAIGN_GROUP
                - CONVERSION
                - CONVERSATION_NODE
                - CONVERSATION_NODE_OPTION_INDEX
                - SERVING_LOCATION
                - CARD_INDEX
                - MEMBER_COMPANY_SIZE
                - MEMBER_INDUSTRY
                - MEMBER_SENIORITY
                - MEMBER_JOB_TITLE
                - MEMBER_JOB_FUNCTION
                - MEMBER_COUNTRY_V2
                - MEMBER_REGION_V2
                - MEMBER_COMPANY
                - PLACEMENT_NAME
                - IMPRESSION_DEVICE_TYPE
                - EVENT_STAGE
            time_granularity:
              title: Time Granularity
              description: "Choose how to group the data in your report by time. The options are:<br>- 'ALL': A single result summarizing the entire time range.<br>- 'DAILY': Group results by each day.<br>- 'MONTHLY': Group results by each month.<br>- 'YEARLY': Group results by each year.<br>Selecting a time grouping helps you analyze trends and patterns over different time periods."
              type: string
              enum:
                - ALL
                - DAILY
                - MONTHLY
                - YEARLY
        default: []
      ad_statistics_reports:
        title: Custom Ad Statistics Reports
        type: array
        items:
          type: object
          title: Ad Statistics Report Configuration
          description: "Config for custom ad Statistics Finder report"
          required:
            - name
            - pivots
            - time_granularity
          properties:
            name:
              title: Report Name
              description: "The name for the custom report."
              type: string
            pivots:
              title: Pivot Categories
              description: "Choose up to three categories to pivot your Statistics Finder report around."
              type: array
              minItems: 1
              maxItems: 3
              uniqueItems: true
              items:
                type: string
                enum:
                  - COMPANY
                  - ACCOUNT
                  - SHARE
                  - CAMPAIGN
                  - CREATIVE
                  - CAMPAIGN_GROUP
                  - CONVERSION
                  - CONVERSATION_NODE
                  - CONVERSATION_NODE_OPTION_INDEX
                  - SERVING_LOCATION
                  - OBJECTIVE_TYPE
                  - CARD_INDEX
                  - PLACEMENT_NAME
                  - IMPRESSION_DEVICE_TYPE
                  - EVENT_STAGE
            time_granularity:
              title: Time Granularity
              description: "Choose how to group the data in your report by time. The options are:<br>- 'ALL': A single result summarizing the entire time range.<br>- 'DAILY': Group results by each day.<br>- 'MONTHLY': Group results by each month.<br>- 'YEARLY': Group results by each year.<br>Selecting a time grouping helps you analyze trends and patterns over different time periods."
              type: string
              enum:
                - ALL
                - DAILY
                - MONTHLY
                - YEARLY
        default: []
      num_workers:
        title: Number of Workers
        description: The number of workers to use for the connector. This is used to limit the number of concurrent requests to the LinkedIn Ads API. If not set, the default is 3 workers.
        type: integer
        default: 3
        minimum: 2
        maximum: 50
  advanced_auth:
    auth_flow_type: oauth2.0
    predicate_key:
      - credentials
      - auth_method
    predicate_value: oAuth2.0
    oauth_config_specification:
      oauth_connector_input_specification:
        scopes:
          - scope: "r_marketing_leadgen_automation"
          - scope: "r_ads_reporting"
          - scope: "r_liteprofile"
          - scope: "r_organization_social"
          - scope: "r_ads"
          - scope: "r_emailaddress"
          - scope: "r_basicprofile"
          - scope: "r_events"
          - scope: "r_organization_admin"
          - scope: "r_ads_leadgen_automation"
          - scope: "r_1st_connections_size"
        consent_url: "https://www.linkedin.com/oauth/v2/authorization?{{client_id_param}}&{{redirect_uri_param}}&response_type=code&{{scopes_param}}&{{state_param}}"
        access_token_url: "https://www.linkedin.com/oauth/v2/accessToken"
        access_token_headers:
          Content-Type: "application/x-www-form-urlencoded"
        access_token_params:
          grant_type: "authorization_code"
          code: "{{ auth_code_value }}"
          client_id: "{{ client_id_value }}"
          client_secret: "{{ client_secret_value }}"
          redirect_uri: "{{ redirect_uri_value }}"
        extract_output:
          - refresh_token
      complete_oauth_output_specification:
        type: object
        properties:
          refresh_token:
            type: string
            path_in_connector_config:
              - credentials
              - refresh_token
      complete_oauth_server_input_specification:
        type: object
        properties:
          client_id:
            type: string
          client_secret:
            type: string
      complete_oauth_server_output_specification:
        type: object
        properties:
          client_id:
            type: string
            path_in_connector_config:
              - credentials
              - client_id
          client_secret:
            type: string
            path_in_connector_config:
              - credentials
              - client_secret
metadata:
  autoImportSchema:
    accounts: false
    organizations: false
    account_users: false
    campaigns: false
    campaign_groups: false
    creatives: false
    conversions: false
    lead_forms: false
    lead_form_responses: false
    videos: false
    ad_campaign_analytics: false
    ad_creative_analytics: false
    ad_impression_device_analytics: false
    ad_member_company_size_analytics: false
    ad_member_country_analytics: false
    ad_member_job_function_analytics: false
    ad_member_job_title_analytics: false
    ad_member_industry_analytics: false
    ad_member_seniority_analytics: false
    ad_member_region_analytics: false
    ad_member_company_analytics: false

schemas:
  accounts:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Accounts"
    additionalProperties: true
    properties:
      test:
        description: Flag indicating if the account is in a test mode.
        type:
          - "null"
          - boolean
      notifiedOnCreativeRejection:
        description: Flag for notifications on creative rejection.
        type:
          - "null"
          - boolean
      notifiedOnNewFeaturesEnabled:
        description: Flag for notifications on new features being enabled.
        type:
          - "null"
          - boolean
      notifiedOnEndOfCampaign:
        description: Flag for notifications on the end of campaign.
        type:
          - "null"
          - boolean
      servingStatuses:
        description: The serving statuses associated with the account.
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - string
      notifiedOnCampaignOptimization:
        description: Flag for notifications on campaign optimization.
        type:
          - "null"
          - boolean
      type:
        description: The type or category of the account.
        type:
          - "null"
          - string
      version:
        description: The version information related to the account.
        type:
          - "null"
          - object
        properties:
          versionTag:
            description: The version tag associated with the account.
            type:
              - "null"
              - string
      reference:
        description: A reference identifier for the account.
        type:
          - "null"
          - string
      notifiedOnCreativeApproval:
        description: Flag for notifications on creative approval.
        type:
          - "null"
          - boolean
      created:
        description: The timestamp indicating when the account was created.
        type:
          - "null"
          - string
        format: date-time
      lastModified:
        description: The timestamp of the last modification made to the account.
        type:
          - "null"
          - string
        format: date-time
      name:
        description: The name of the account.
        type:
          - "null"
          - string
      currency:
        description: The currency used for financial transactions in the account.
        type:
          - "null"
          - string
      id:
        description: The unique identifier for the account.
        type:
          - "null"
          - integer
      status:
        description: The status of the account.
        type:
          - "null"
          - string

  organizations:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Organizations"
    additionalProperties: true
    properties:
      organization:
        description: The URN of the organization (e.g. urn:li:organization:12345).
        type:
          - "null"
          - string
      organizationTarget:
        description: The URN of the organization as returned by API responses that use the organizationTarget field name instead of organization.
        type:
          - "null"
          - string
      roleAssignee:
        description: The URN of the member assigned the role.
        type:
          - "null"
          - string
      state:
        description: The state of the organization access (e.g. APPROVED).
        type:
          - "null"
          - string
      role:
        description: The role of the member in the organization (e.g. ADMINISTRATOR, DIRECT_SPONSORED_CONTENT_POSTER).
        type:
          - "null"
          - string
      created:
        description: Rest.li audit stamp of the access grant creation - `actor` (member URN) and `time` (epoch milliseconds), kept as returned by the API.
        type:
          - "null"
          - object
        properties:
          actor:
            type:
              - "null"
              - string
          time:
            type:
              - "null"
              - integer
      lastModified:
        description: Rest.li audit stamp of the last modification of the access grant - `actor` (member URN) and `time` (epoch milliseconds), kept as returned by the API.
        type:
          - "null"
          - object
        properties:
          actor:
            type:
              - "null"
              - string
          time:
            type:
              - "null"
              - integer

  account_users:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Account Users"
    additionalProperties: true
    properties:
      account:
        description: The account associated with the user
        type:
          - "null"
          - string
      created:
        description: The date and time when the user account was created
        type:
          - "null"
          - string
        format: date-time
      lastModified:
        description: The date and time when the user account was last modified
        type:
          - "null"
          - string
        format: date-time
      role:
        description: The role assigned to the user in the account
        type:
          - "null"
          - string
      user:
        description: The user details including name, email, etc.
        type:
          - "null"
          - string

  campaigns:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Campaigns"
    additionalProperties: true
    properties:
      targetingCriteria:
        description: Criteria for targeting in the campaign.
        type:
          - "null"
          - object
        properties:
          include:
            description: Criteria to include in targeting.
            type:
              - "null"
              - object
            properties:
              and:
                type:
                  - "null"
                  - array
                items:
                  type:
                    - "null"
                    - object
                  properties:
                    type:
                      description: The type of targeting to include.
                      type:
                        - "null"
                        - string
                    values:
                      type:
                        - "null"
                        - array
                      items:
                        description: Values to include for the specified type.
                        type:
                          - "null"
                          - string
          exclude:
            description: Criteria to exclude in targeting.
            type:
              - "null"
              - object
            properties:
              or:
                type:
                  - "null"
                  - array
                items:
                  type:
                    - "null"
                    - object
                  properties:
                    type:
                      description: The type of targeting to exclude.
                      type:
                        - "null"
                        - string
                    values:
                      type:
                        - "null"
                        - array
                      items:
                        description: Values to exclude for the specified type.
                        type:
                          - "null"
                          - string
      servingStatuses:
        description: The serving statuses of the campaign.
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - string
      type:
        description: The type of campaign.
        type:
          - "null"
          - string
      locale:
        description: The locale settings for the campaign.
        type:
          - "null"
          - object
        properties:
          country:
            description: The country setting for the campaign.
            type:
              - "null"
              - string
          language:
            description: The language setting for the campaign.
            type:
              - "null"
              - string
      version:
        description: The version information for the campaign.
        type:
          - "null"
          - object
        properties:
          versionTag:
            description: The version tag for the campaign.
            type:
              - "null"
              - string
      associatedEntity:
        description: The entity associated with the campaign.
        type:
          - "null"
          - string
      runSchedule:
        description: The schedule for running the campaign.
        type:
          - "null"
          - object
        properties:
          start:
            description: The start date of the campaign schedule.
            type:
              - "null"
              - integer
          end:
            description: The end date of the campaign schedule.
            type:
              - "null"
              - integer
      optimizationTargetType:
        description: The type of optimization target for the campaign.
        type:
          - "null"
          - string
      created:
        description: The date and time when the campaign was created.
        type:
          - "null"
          - string
        format: date-time
      lastModified:
        description: The date and time when the campaign was last modified.
        type:
          - "null"
          - string
        format: date-time
      campaignGroup:
        description: The group to which the campaign belongs.
        type:
          - "null"
          - string
      dailyBudget:
        description: The daily budget set for the campaign.
        type:
          - "null"
          - object
        properties:
          amount:
            description: The daily budget amount for the campaign.
            type:
              - "null"
              - string
          currencyCode:
            description: The currency code for the daily budget amount.
            type:
              - "null"
              - string
      totalBudget:
        description: The total budget amount for the campaign.
        type:
          - "null"
          - object
        properties:
          amount:
            description: The total budget amount.
            type:
              - "null"
              - string
          currencyCode:
            description: The currency code for the total budget amount.
            type:
              - "null"
              - string
      unitCost:
        description: The unit cost for the campaign.
        type:
          - "null"
          - object
        properties:
          amount:
            description: The unit cost amount.
            type:
              - "null"
              - string
          currencyCode:
            description: The currency code for the unit cost amount.
            type:
              - "null"
              - string
      creativeSelection:
        description: Information about the creative selection for the campaign.
        type:
          - "null"
          - string
      costType:
        description: The type of cost associated with the campaign.
        type:
          - "null"
          - string
      name:
        description: The name of the campaign.
        type:
          - "null"
          - string
      offsiteDeliveryEnabled:
        description: Indicates if offsite delivery is enabled for the campaign.
        type:
          - "null"
          - boolean
      id:
        description: The unique identifier of the campaign.
        type:
          - "null"
          - integer
      audienceExpansionEnabled:
        description: Indicates if audience expansion is enabled for this campaign.
        type:
          - "null"
          - boolean
      test:
        description: Indicates if the campaign is a test campaign.
        type:
          - "null"
          - boolean
      account:
        description: The account associated with the campaign data.
        type:
          - "null"
          - string
      status:
        description: The status of the campaign.
        type:
          - "null"
          - string
      storyDeliveryEnabled:
        description: Indicates if story delivery is enabled for the campaign.
        type:
          - "null"
          - boolean
      pacingStrategy:
        description: The pacing strategy for the campaign.
        type:
          - "null"
          - string
      format:
        description: The format of the campaign.
        type:
          - "null"
          - string
      objectiveType:
        description: The type of objective for the campaign.
        type:
          - "null"
          - string
      offsitePreferences:
        description: Preferences related to offsite delivery.
        type:
          - "null"
          - object
        properties:
          iabCategories:
            description: IAB categories preferences.
            type:
              - "null"
              - object
            properties:
              exclude:
                description: Excluded IAB categories.
                type:
                  - "null"
                  - array
          publisherRestrictionFiles:
            description: Publisher restriction files preferences.
            type:
              - "null"
              - object
            properties:
              include:
                description: Included publisher restriction files.
                type:
                  - "null"
                  - array
              exclude:
                description: Excluded publisher restriction files.
                type:
                  - "null"
                  - array

  campaign_groups:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Campaign Groups"
    additionalProperties: true
    properties:
      runSchedule:
        description: Schedule for running the campaign group.
        type:
          - "null"
          - object
        properties:
          start:
            description: The start date and time of the campaign group run schedule.
            type:
              - "null"
              - integer
          end:
            description: The end date and time of the campaign group run schedule.
            type:
              - "null"
              - integer
      created:
        description: The date and time when the campaign group was created.
        type:
          - "null"
          - string
        format: date-time
      lastModified:
        description: The date and time when the campaign group was last modified.
        type:
          - "null"
          - string
        format: date-time
      name:
        description: Name of the campaign group.
        type:
          - "null"
          - string
      test:
        description: Indicates if the campaign group is a test campaign.
        type:
          - "null"
          - boolean
      totalBudget:
        description: Total budget allocated for the campaign group.
        type:
          - "null"
          - object
        properties:
          amount:
            description: The total budget amount.
            type:
              - "null"
              - string
          currencyCode:
            description: The currency code of the total budget.
            type:
              - "null"
              - string
      servingStatuses:
        description: List of serving statuses for the campaign group.
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - string
      backfilled:
        description: Indicates if the campaign group was backfilled.
        type:
          - "null"
          - boolean
      id:
        description: Unique identifier for the campaign group.
        type:
          - "null"
          - integer
      account:
        description: The account associated with the campaign group.
        type:
          - "null"
          - string
      status:
        description: Current status of the campaign group.
        type:
          - "null"
          - string
      allowedCampaignTypes:
        description: List of campaign types allowed for this campaign group.
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - string

  creatives:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Creatives"
    additionalProperties: true
    properties:
      servingHoldReasons:
        description: Reasons for holding the creative from serving.
        type:
          - "null"
          - array
        items:
          description: List of reasons for holding the creative.
          type:
            - "null"
            - string
      lastModifiedAt:
        description: The timestamp when the creative was last modified.
        type:
          - "null"
          - integer
      lastModifiedBy:
        description: The user who last modified the creative.
        type:
          - "null"
          - string
      content:
        description: The actual content of the creative.
        type:
          - "null"
          - object
      createdAt:
        description: The timestamp when the creative was created.
        type:
          - "null"
          - integer
      isTest:
        description: Boolean indicating if the creative is a test creative.
        type:
          - "null"
          - boolean
      createdBy:
        description: The user who created the creative.
        type:
          - "null"
          - string
      review:
        description: Review information for the creative.
        type:
          - "null"
          - object
        properties:
          status:
            description: The current status of the creative review.
            type:
              - "null"
              - string
          rejectionReasons:
            description: Reasons why the creative was rejected during review.
            type:
              - "null"
              - array
      name:
        description: The name of the creative.
        type:
          - "null"
          - string
      isServing:
        description: Boolean indicating if the creative is currently serving.
        type:
          - "null"
          - boolean
      campaign:
        description: The campaign to which the creative belongs.
        type:
          - "null"
          - string
      id:
        description: The unique identifier of the creative.
        type:
          - "null"
          - string
      intendedStatus:
        description: The intended status of the creative.
        type:
          - "null"
          - string
      account:
        description: The account associated with the creative.
        type:
          - "null"
          - string
      leadgenCallToAction:
        description: Call-to-action information for lead generation purposes.
        type:
          - "null"
          - object
        properties:
          destination:
            description: The destination for the call-to-action.
            type:
              - "null"
              - string
          label:
            description: The label of the call-to-action.
            type:
              - "null"
              - string

  conversions:
    $schema: https://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Conversions"
    properties:
      attributionType:
        description: The type of attribution for the conversion.
        type:
          - "null"
          - string
      account:
        description: The account associated with the conversion data.
        type:
          - "null"
          - string
      campaigns:
        description: List of campaigns related to the conversion.
        type:
          - "null"
          - array
        items:
          description: Individual campaign data.
          type:
            - "null"
            - string
      created:
        description: Timestamp of when the conversion was created.
        type:
          - "null"
          - integer
      enabled:
        description: Flag indicating if the conversion tracking is enabled.
        type:
          - "null"
          - boolean
      id:
        description: Unique identifier for the conversion.
        type:
          - "null"
          - integer
      imagePixelTag:
        description: Pixel tag used for tracking the conversion.
        type:
          - "null"
          - string
      name:
        description: Name of the conversion.
        type:
          - "null"
          - string
      type:
        description: Type of conversion.
        type:
          - "null"
          - string
      latestFirstPartyCallbackAt:
        description: Timestamp of the latest first-party callback for the conversion.
        type:
          - "null"
          - integer
      postClickAttributionWindowSize:
        description: Window size for post-click attribution.
        type:
          - "null"
          - integer
      viewThroughAttributionWindowSize:
        description: Window size for view-through attribution.
        type:
          - "null"
          - integer
      lastCallbackAt:
        description: Timestamp of the last callback for the conversion.
        type:
          - "null"
          - integer
      lastModified:
        description: Timestamp of the last modification made to the conversion.
        type:
          - "null"
          - integer
      value:
        description: Value associated with the conversion.
        type:
          - "null"
          - object
        properties:
          amount:
            description: Numeric value of the amount.
            type:
              - "null"
              - string
          currencyCode:
            description: Currency code of the value.
            type:
              - "null"
              - string
      associatedCampaigns:
        description: Campaigns associated with the conversion.
        type:
          - "null"
          - array
      urlMatchRuleExpression:
        description: Expression used for matching URLs for attribution.
        type:
          - "null"
          - array
      urlRules:
        description: Rules for URL matching in the conversion.
        type:
          - "null"
          - array

  lead_forms:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Lead forms"
    description: |
      Lead Forms are used to request data from members responding to the Lead Form.
      Lead Forms can include multiple questions, hidden fields, and custom consent checkboxes.
      Many of these components are structured as sub-objects of the Lead Form.
      For details: https://learn.microsoft.com/en-us/linkedin/marketing/lead-sync/leadsync?view=li-lms-2025-02&tabs=http#lead-form-schema
    additionalProperties: true
    properties:
      id:
        description: Numerical identifier for the form.
        type:
          - integer
      name:
        description: Name of the Lead Form provided by the owner.
        type:
          - "null"
          - string
      owner:
        description: |
          URN that identifies the owner of the Lead Form.
          It's a Union of sponsoredAccount and organization.
          sponsoredAccount is an URN of SponsoredAccountUrn that indicates the account of the advertiser.
          organization is an URN of OrganizationUrn that indicates the company account of the marketer.
        type:
          - "null"
          - object
        properties:
          sponsoredAccount:
            type:
              - "null"
              - string
      state:
        description: Information about the current state of the Lead Form.
        type:
          - "null"
          - string
      content:
        description: Content of the Lead Form which will be displayed to the viewer.
        type:
          - "null"
          - object
        properties:
          headline:
            description: Headline of the form.
            type:
              - "null"
              - object
          description:
            description: Description of the form. Optional since the owner may choose to not have this information.
            type:
              - "null"
              - object
          questions:
            description: Questions to request information from the viewer. At least one question should be present.
            type:
              - "null"
              - array
            items:
              type:
                - "null"
                - object
              properties:
                questionId:
                  description: Unique identifier of the LeadGenFormQuestion.
                  type:
                    - "null"
                    - integer
                name:
                  description: Name of the question, shown to the owner only.
                  type:
                    - "null"
                    - string
                question:
                  description: The question prompt, shown to the viewer.
                  type:
                    - "null"
                    - object
                textPrompt:
                  description: The description or hint of the question, shown to the viewer. Empty in case No hint is provided.
                  type:
                    - "null"
                    - string
                predefinedField:
                  description: |
                    The predefined field that the question is requesting.
                    This field is used for specifying viewer specific fields(e.g. First name, City, School, etc.) that should be used to prefill the question response.
                    Customized questions do not request a predefined field and will leave this field empty.
                  type:
                    - "null"
                    - string
                responseEditable:
                  description: True if the member viewing the form can edit a pre-filled form response. Default is true.
                  type:
                    - "null"
                    - boolean
                responseRequired:
                  description: True if the response is required for the question. Default is true.
                  type:
                    - "null"
                    - boolean
                questionDetails:
                  description: The specific details of the question including default answer, answer restrictions etc. We allow text and selection questions.
                  type:
                    - "null"
                    - object
                questionSubmissionCriteria:
                  description: |
                    The criteria for submission of response for the question.
                    For example: allow only Non-freemium emails for the work email form question.
                    A question submission criteria is exclusive to the predefined field tied to the question.
                  type:
                    - "null"
                    - object
                label:
                  description: The label of the question specified by marketers. These labels for the questions are unique within the context of a single form.
                  type:
                    - "null"
                    - string

          legalInfo:
            description: Legal information displayed alongside the Lead Form.
            type:
              - "null"
              - object
          postSubmissionInfo:
            description: |
              Information displayed to the user after submitting the form (e.g. thank you message, etc.).
              Optional since not all use cases require a post submission experience.
            type:
              - "null"
              - object
      created:
        description: An epoch time corresponding to the creation of the form.
        type:
          - "null"
          - integer
      lastModified:
        description: An epoch time corresponding to the last modified of of the form.
        type:
          - "null"
          - integer
      creationLocale:
        description: |
          Locale of the entity.
          This field serves as the preferred locale for all fields within the Lead Form with an object type that is capable of localization, such as MultiLocaleString.
        type:
          - "null"
          - object
      hiddenFields:
        description: |
          Hidden fields used by the owner to track key attributes of the form that generated the lead.
          The field is empty if the owner chooses to not append any tracking attributes to the Lead Form.
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - object
          properties:
            name:
              type:
                - "null"
                - string
            value:
              type:
                - "null"
                - string
      reviewInfo:
        description: |
          Latest information about the content review of the Lead Form.
          It will not be present if the form has not been reviewed by the review pipeline.
        type:
          - "null"
          - object
      versionId:
        description: The version ID of the form. This is a derived field and is generated on the server side.
        type:
          - "null"
          - integer
      versionTag:
        description: The number of times the form has been modified.
        type:
          - "null"
          - string

  lead_form_responses:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Lead form responses"
    description: |
      The Lead Form Responses API returns the response data for leads that filled out a Lead Form.
      Collecting Lead Form responses requires the viewer is the owner of the Lead Form.
      For details: https://learn.microsoft.com/en-us/linkedin/marketing/lead-sync/leadsync?view=li-lms-2025-02&tabs=http#lead-form-response-schema
    additionalProperties: true
    properties:
      id:
        description: Unique id to identify the Lead Form Response.
        type:
          - "null"
          - string
      leadType:
        description: Type of the lead representing the origination of the lead.
        type:
          - "null"
          - string
      form:
        description: URN identifying which form this FormResponse belongs to.
        type:
          - "null"
          - object
      owner:
        description: |
          Owner of this Lead Form Response.
          It is a Union of sponsoredAccount and organization.
          sponsoredAccount is an URN of SponsoredAccountUrn that indicates the ad account of the advertiser.
          organization is an URN of OrganizationUrn that indicates the company page of the advertiser.
        type:
          - "null"
          - object
        properties:
          sponsoredAccount:
            type:
              - "null"
              - string
      ownerInfo:
        description: Record containing entity info that owns this Lead Form Response. It's a optional Union of sponsoredAccountInfo and organizationInfo.
        type:
          - "null"
          - object
      leadMetadata:
"""
