"""Searchable copy of airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml (part 4 of 8) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-linkedin-ads/manifest.yaml'
PART = 4
TOTAL_PARTS = 8

CONTENT = """\
        description: Metadata of a lead. This field is optional for test leads and other use cases where sponsored lead metadata (e.g. campaign) may not be relevant. If there is no value, the field is not returned.
        type:
          - "null"
          - object
        properties:
          sponsoredLeadMetadata:
            type:
              - "null"
              - object
            properties:
              campaign:
                type:
                  - "null"
                  - string
      leadMetadataInfo:
        description: Record containing a subset of fields resolved on demand from the lead metadata references (e.g. campaign name , campaign type). If there is no value, an empty object is returned.
        type:
          - "null"
          - object
      associatedEntity:
        description: URN identifying which entity the lead is associated with. This field is optional for test leads and other use cases where leads don't have any associatedEntity. If there is no value, the field is not returned.
        type:
          - "null"
          - object
        properties:
          associatedCreative:
            type:
              - "null"
              - string
      associatedEntityInfo:
        description: Record containing useful fields (creative status, ugc reference etc.) resolved on demand from the associated entity object. If there is no value, an empty object is returned.
        type:
          - "null"
          - object
      submittedAt:
        description: An epoch timestamp that recording when the form response was submitted.
        type:
          - "null"
          - integer
      responseId:
        description: The unique identifier for the form response generated in the front-end when a submitter submits the response.
        type:
          - "null"
          - object
      formResponse:
        description: Answers provided by the form submitter.
        type:
          - "null"
          - object
        properties:
          answers:
            type:
              - "null"
              - array
            items:
              type:
                - "null"
                - object
              properties:
                questionId:
                  type:
                    - "null"
                    - integer
                answerDetails:
                  type:
                    - "null"
                    - object
                  properties:
                    textQuestionAnswer:
                      type:
                        - "null"
                        - object
                      properties:
                        answer:
                          type:
                            - "null"
                            - string
                    multipleChoiceAnswer:
                      type:
                        - "null"
                        - object
                      properties:
                        options:
                          type:
                            - "null"
                            - array
                          items:
                            type:
                              - "null"
                              - integer
          consentResponses:
            type:
              - "null"
              - array
      testLead:
        description: Whether this is a test lead created for testing purposes.
        type:
          - "null"
          - boolean
      submitter:
        description: |
          From version 202408 onwards, Guest Leads (when a user submits a form without being logged in) submitted to lead forms, submitter field is treated as a null field and omitted from the JSON response.
          For non-guest leads, the submitter field will still be included in the response and will provide the person's URN. Ex: "submitter": "urn:li:person:MpGcnvaU_p".	Yes
        type:
          - "null"
          - string
      versionedLeadGenFormUrn:
        description: URN identifying which form this FormResponse belongs to.
        type:
          - "null"
          - string

  videos:
    $schema: http://json-schema.org/draft-07/schema#
    type:
      - "null"
      - object
    title: "Videos"
    description: |
      Videos referenced by the sponsored accounts' ad creatives, including their duration and other media metadata.
      Joinable with the creatives stream through the post referenced in creative.content.reference.
      For details: https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/videos-api
    additionalProperties: true
    properties:
      id:
        description: The unique video URN (e.g. urn:li:video:C4E10AQGUkQY7trgh-Q).
        type:
          - string
      owner:
        description: URN of the entity that owns this asset. Can be a person or organization URN.
        type:
          - "null"
          - string
      duration:
        description: The length of the video in milliseconds. Empty if the media asset isn't available or failed processing.
        type:
          - "null"
          - integer
      aspectRatioWidth:
        description: Aspect ratio width of the media. For media with a 16:9 ratio, it's 16.
        type:
          - "null"
          - number
      aspectRatioHeight:
        description: Aspect ratio height of the media. For media with a 16:9 ratio, it's 9.
        type:
          - "null"
          - number
      downloadUrl:
        description: Public URL to download/view the media asset.
        type:
          - "null"
          - string
      downloadUrlExpiresAt:
        description: Milliseconds since the epoch when the download URL expires.
        type:
          - "null"
          - integer
      thumbnail:
        description: Public URL of the video thumbnail image.
        type:
          - "null"
          - string
      captions:
        description: Public URL of the video caption file.
        type:
          - "null"
          - string
      status:
        description: "Processing status of the asset: PROCESSING, PROCESSING_FAILED, AVAILABLE or WAITING_UPLOAD."
        type:
          - "null"
          - string
      processingFailureReason:
        description: Reason for video processing failure. Only present if status is PROCESSING_FAILED.
        type:
          - "null"
          - string
      mediaLibraryMetadata:
        description: Metadata for assets stored in the media library, tied to a specific sponsored account.
        type:
          - "null"
          - object
        properties:
          associatedAccount:
            description: The associated account that owns the media library (e.g. urn:li:sponsoredAccount:123).
            type:
              - "null"
              - string
          assetName:
            description: The name of the asset in the associated account's library.
            type:
              - "null"
              - string
          mediaLibraryStatus:
            description: Status of the asset's entry in the media library (ACTIVE or ARCHIVED).
            type:
              - "null"
              - string

  ad_campaign_analytics:
    $schema: "http://json-schema.org/draft-07/schema#"
    type:
      - "null"
      - object
    title: "Ad Campaign Analytics"
    additionalProperties: true
    properties:
      actionClicks:
        description: "The number of clicks on action buttons in the ad."
        type:
          - "null"
          - number
      adUnitClicks:
        description: "The number of clicks on ad unit components."
        type:
          - "null"
          - number
      approximateMemberReach:
        description: "An approximation of unique ad impressions."
        type:
          - "null"
          - number
      cardClicks:
        description: "The number of clicks on interactive card elements."
        type:
          - "null"
          - number
      cardImpressions:
        description: "The number of times interactive cards were displayed."
        type:
          - "null"
          - number
      clicks:
        description: "Total number of clicks on the ad."
        type:
          - "null"
          - number
      commentLikes:
        description: "The count of likes on comments related to the ad."
        type:
          - "null"
          - number
      comments:
        description: "The number of comments on the ad."
        type:
          - "null"
          - number
      companyPageClicks:
        description: "Clicks on the company page associated with the ad."
        type:
          - "null"
          - number
      conversionValueInLocalCurrency:
        description: "Conversion value in the local currency."
        type:
          - "null"
          - number
      costInLocalCurrency:
        description: "Cost of ad campaign in the local currency."
        type:
          - "null"
          - number
      costInUsd:
        description: "Cost of ad campaign in USD."
        type:
          - "null"
          - number
      documentCompletions:
        description: "Number of completions for document views."
        type:
          - "null"
          - number
      documentFirstQuartileCompletions:
        description: "Completions for first quartile of document views."
        type:
          - "null"
          - number
      documentMidpointCompletions:
        description: "Completions for midpoint of document views."
        type:
          - "null"
          - number
      documentThirdQuartileCompletions:
        description: "Completions for third quartile of document views."
        type:
          - "null"
          - number
      downloadClicks:
        description: "Clicks on download links in the ad."
        type:
          - "null"
          - number
      end_date:
        description: "End date of the ad analytics data."
        type:
          - "null"
          - string
        format: "date"
      externalWebsiteConversions:
        description: "Conversions that lead to external websites."
        type:
          - "null"
          - number
      externalWebsitePostClickConversions:
        description: "Post-click conversions on external websites."
        type:
          - "null"
          - number
      externalWebsitePostViewConversions:
        description: "Post-view conversions on external websites."
        type:
          - "null"
          - number
      follows:
        description: "Number of follows generated by the ad."
        type:
          - "null"
          - number
      fullScreenPlays:
        description: "Number of times videos were played in fullscreen mode."
        type:
          - "null"
          - number
      impressions:
        description: "Total number of times the ad was displayed."
        type:
          - "null"
          - number
      jobApplications:
        description: "Number of job applications initiated through the ad."
        type:
          - "null"
          - number
      jobApplyClicks:
        description: "Clicks on apply job button in the ad."
        type:
          - "null"
          - number
      landingPageClicks:
        description: "Clicks on the landing page associated with the ad."
        type:
          - "null"
          - number
      leadGenerationMailContactInfoShares:
        description: "Shares of contact information through lead generation."
        type:
          - "null"
          - number
      leadGenerationMailInterestedClicks:
        description: "Clicks on expressing interest through lead generation mail."
        type:
          - "null"
          - number
      likes:
        description: "Total likes received on the ad."
        type:
          - "null"
          - number
      oneClickLeadFormOpens:
        description: "Number of times lead forms were opened in one click."
        type:
          - "null"
          - number
      oneClickLeads:
        description: "Leads generated in one click."
        type:
          - "null"
          - number
      opens:
        description: "The number of times the ad was opened or expanded."
        type:
          - "null"
          - number
      otherEngagements:
        description: "Engagements other than clicks on the ad."
        type:
          - "null"
          - number
      pivotValues:
        description: "Values used for pivoting the analytics."
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - string
      string_of_pivot_values:
        type:
          - "null"
          - string
      postClickJobApplications:
        description: "Job applications initiated post-clicking on the ad."
        type:
          - "null"
          - number
      postClickJobApplyClicks:
        description: "Clicks on apply job button post-clicking on the ad."
        type:
          - "null"
          - number
      postClickRegistrations:
        description: "Registrations completed post-clicking on the ad."
        type:
          - "null"
          - number
      postViewJobApplications:
        description: "Job applications initiated post-viewing the ad."
        type:
          - "null"
          - number
      postViewJobApplyClicks:
        description: "Clicks on apply job button post-viewing the ad."
        type:
          - "null"
          - number
      postViewRegistrations:
        description: "Registrations completed post-viewing the ad."
        type:
          - "null"
          - number
      reactions:
        description: "Total reactions (e.g., like, love, celebrate) on the ad."
        type:
          - "null"
          - number
      registrations:
        description: "Total registrations completed through the ad."
        type:
          - "null"
          - number
      sends:
        description: "Number of messages sent through the ad."
        type:
          - "null"
          - number
      shares:
        description: "Total shares generated by the ad."
        type:
          - "null"
          - number
      start_date:
        description: "Start date of the ad analytics data."
        type:
          - "null"
          - string
        format: "date"
      talentLeads:
        description: "Number of leads related to talent acquisition."
        type:
          - "null"
          - number
      textUrlClicks:
        description: "Clicks on text URLs within the ad."
        type:
          - "null"
          - number
      totalEngagements:
        description: "Total number of engagements on the ad."
        type:
          - "null"
          - number
      validWorkEmailLeads:
        description: "Leads generated through valid work emails."
        type:
          - "null"
          - number
      videoCompletions:
        description: "Number of times videos were watched till completion."
        type:
          - "null"
          - number
      videoFirstQuartileCompletions:
        description: "Completions for first quartile of video views."
        type:
          - "null"
          - number
      videoMidpointCompletions:
        description: "Completions for midpoint of video views."
        type:
          - "null"
          - number
      videoStarts:
        description: "Total video starts initiated by users."
        type:
          - "null"
          - number
      videoThirdQuartileCompletions:
        description: "Completions for third quartile of video views."
        type:
          - "null"
          - number
      videoViews:
        description: "Total views of videos in the ad."
        type:
          - "null"
          - number
      viralCardClicks:
        description: "Clicks on interactive card components in viral distribution."
        type:
          - "null"
          - number
      viralCardImpressions:
        description: "Impressions of interactive cards in viral distribution."
        type:
          - "null"
          - number
      viralClicks:
        description: "Total clicks in viral distribution of the ad."
        type:
          - "null"
          - number
      viralCommentLikes:
        description: "Likes received on comments in viral distribution."
        type:
          - "null"
          - number
      viralComments:
        description: "Number of comments in viral distribution of the ad."
        type:
          - "null"
          - number
      viralCompanyPageClicks:
        description: "Clicks on the company page in viral distribution."
        type:
          - "null"
          - number
      viralDocumentCompletions:
        description: "Complete views of documents in viral distribution."
        type:
          - "null"
          - number
      viralDocumentFirstQuartileCompletions:
        description: "First quartile completions of documents in viral distribution."
        type:
          - "null"
          - number
      viralDocumentMidpointCompletions:
        description: "Midpoint completions of documents in viral distribution."
        type:
          - "null"
          - number
      viralDocumentThirdQuartileCompletions:
        description: "Third quartile completions of documents in viral distribution."
        type:
          - "null"
          - number
      viralDownloadClicks:
        description: "Clicks on downloads in viral distribution of the ad."
        type:
          - "null"
          - number
      viralExternalWebsiteConversions:
        description: "External website conversions in viral distribution."
        type:
          - "null"
          - number
      viralExternalWebsitePostClickConversions:
        description: "Post-click conversions on external websites in viral distribution."
        type:
          - "null"
          - number
      viralExternalWebsitePostViewConversions:
        description: "Post-view conversions on external websites in viral distribution."
        type:
          - "null"
          - number
      viralFollows:
        description: "Follows generated in viral distribution of the ad."
        type:
          - "null"
          - number
      viralFullScreenPlays:
        description: "Fullscreen video plays in viral distribution."
        type:
          - "null"
          - number
      viralImpressions:
        description: "Total impressions in viral distribution of the ad."
        type:
          - "null"
          - number
      viralJobApplications:
        description: "Job applications initiated in viral distribution."
        type:
          - "null"
          - number
      viralJobApplyClicks:
        description: "Clicks on apply job button in viral distribution of the ad."
        type:
          - "null"
          - number
      viralLandingPageClicks:
        description: "Clicks on landing page in viral distribution."
        type:
          - "null"
          - number
      viralLikes:
        description: "Total likes in viral distribution of the ad."
        type:
          - "null"
          - number
      viralOneClickLeadFormOpens:
        description: "One-click lead form opens in viral distribution."
        type:
          - "null"
          - number
      viralOneClickLeads:
        description: "Leads generated in one click in viral distribution."
        type:
          - "null"
          - number
      viralOtherEngagements:
        description: "Other engagements in viral distribution of the ad."
        type:
          - "null"
          - number
      viralPostClickJobApplications:
        description: "Job applications initiated post-clicking in viral distribution."
        type:
          - "null"
          - number
      viralPostClickJobApplyClicks:
        description: "Clicks on apply job button post-clicking in viral distribution."
        type:
          - "null"
          - number
      viralPostClickRegistrations:
        description: "Registrations completed post-clicking in viral distribution."
        type:
          - "null"
          - number
      viralPostViewJobApplications:
        description: "Job applications initiated post-viewing in viral distribution."
        type:
          - "null"
          - number
      viralPostViewJobApplyClicks:
        description: "Clicks on apply job button post-viewing in viral distribution."
        type:
          - "null"
          - number
      viralPostViewRegistrations:
        description: "Registrations completed post-viewing in viral distribution."
        type:
          - "null"
          - number
      viralReactions:
        description: "Total reactions in viral distribution of the ad."
        type:
          - "null"
          - number
      viralRegistrations:
        description: "Total registrations in viral distribution of the ad."
        type:
          - "null"
          - number
      viralShares:
        description: "Total shares in viral distribution of the ad."
        type:
          - "null"
          - number
      viralTotalEngagements:
        description: "Total engagements in viral distribution of the ad."
        type:
          - "null"
          - number
      viralVideoCompletions:
        description: "Completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoFirstQuartileCompletions:
        description: "First quartile completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoMidpointCompletions:
        description: "Midpoint completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoStarts:
        description: "Total video starts in viral distribution of the ad."
        type:
          - "null"
          - number
      viralVideoThirdQuartileCompletions:
        description: "Third quartile completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoViews:
        description: "Total views of videos in viral distribution of the ad."
        type:
          - "null"
          - number
      pivot:
        type:
          - "null"
          - string
      sponsoredCampaign:
        type:
          - "null"
          - string

  ad_creative_analytics:
    $schema: "http://json-schema.org/draft-07/schema#"
    type:
      - "null"
      - object
    title: "Ad Creative Analytics"
    additionalProperties: true
    properties:
      actionClicks:
        description: "The number of clicks on action buttons in the ad."
        type:
          - "null"
          - number
      adUnitClicks:
        description: "The number of clicks on ad unit components."
        type:
          - "null"
          - number
      approximateMemberReach:
        description: "An approximation of unique ad impressions."
        type:
          - "null"
          - number
      cardClicks:
        description: "The number of clicks on interactive card elements."
        type:
          - "null"
          - number
      cardImpressions:
        description: "The number of times interactive cards were displayed."
        type:
          - "null"
          - number
      clicks:
        description: "Total number of clicks on the ad."
        type:
          - "null"
          - number
      commentLikes:
        description: "The count of likes on comments related to the ad."
        type:
          - "null"
          - number
      comments:
        description: "The number of comments on the ad."
        type:
          - "null"
          - number
      companyPageClicks:
        description: "Clicks on the company page associated with the ad."
        type:
          - "null"
          - number
      conversionValueInLocalCurrency:
        description: "Conversion value in the local currency."
        type:
          - "null"
          - number
      costInLocalCurrency:
        description: "Cost of ad campaign in the local currency."
        type:
          - "null"
          - number
      costInUsd:
        description: "Cost of ad campaign in USD."
        type:
          - "null"
          - number
      documentCompletions:
        description: "Number of completions for document views."
        type:
          - "null"
          - number
      documentFirstQuartileCompletions:
        description: "Completions for first quartile of document views."
        type:
          - "null"
          - number
      documentMidpointCompletions:
        description: "Completions for midpoint of document views."
        type:
          - "null"
          - number
      documentThirdQuartileCompletions:
        description: "Completions for third quartile of document views."
        type:
          - "null"
          - number
      downloadClicks:
        description: "Clicks on download links in the ad."
        type:
          - "null"
          - number
      end_date:
        description: "End date of the ad analytics data."
        type:
          - "null"
          - string
        format: "date"
      externalWebsiteConversions:
        description: "Conversions that lead to external websites."
        type:
          - "null"
          - number
      externalWebsitePostClickConversions:
        description: "Post-click conversions on external websites."
        type:
          - "null"
          - number
      externalWebsitePostViewConversions:
        description: "Post-view conversions on external websites."
        type:
          - "null"
          - number
      follows:
        description: "Number of follows generated by the ad."
        type:
          - "null"
          - number
      fullScreenPlays:
        description: "Number of times videos were played in fullscreen mode."
        type:
          - "null"
          - number
      impressions:
        description: "Total number of times the ad was displayed."
        type:
          - "null"
          - number
      jobApplications:
        description: "Number of job applications initiated through the ad."
        type:
          - "null"
          - number
      jobApplyClicks:
        description: "Clicks on apply job button in the ad."
        type:
          - "null"
          - number
      landingPageClicks:
        description: "Clicks on the landing page associated with the ad."
        type:
          - "null"
          - number
      leadGenerationMailContactInfoShares:
        description: "Shares of contact information through lead generation."
        type:
          - "null"
          - number
      leadGenerationMailInterestedClicks:
        description: "Clicks on expressing interest through lead generation mail."
        type:
          - "null"
          - number
      likes:
        description: "Total likes received on the ad."
        type:
          - "null"
          - number
      oneClickLeadFormOpens:
        description: "Number of times lead forms were opened in one click."
        type:
          - "null"
          - number
      oneClickLeads:
        description: "Leads generated in one click."
        type:
          - "null"
          - number
      opens:
        description: "The number of times the ad was opened or expanded."
        type:
          - "null"
          - number
      otherEngagements:
        description: "Engagements other than clicks on the ad."
        type:
          - "null"
          - number
      pivotValues:
        description: "Values used for pivoting the analytics."
        type:
          - "null"
          - array
        items:
          type:
            - "null"
            - string
      string_of_pivot_values:
        type:
          - "null"
          - string
      postClickJobApplications:
        description: "Job applications initiated post-clicking on the ad."
        type:
          - "null"
          - number
      postClickJobApplyClicks:
        description: "Clicks on apply job button post-clicking on the ad."
        type:
          - "null"
          - number
      postClickRegistrations:
        description: "Registrations completed post-clicking on the ad."
        type:
          - "null"
          - number
      postViewJobApplications:
        description: "Job applications initiated post-viewing the ad."
        type:
          - "null"
          - number
      postViewJobApplyClicks:
        description: "Clicks on apply job button post-viewing the ad."
        type:
          - "null"
          - number
      postViewRegistrations:
        description: "Registrations completed post-viewing the ad."
        type:
          - "null"
          - number
      reactions:
        description: "Total reactions (e.g., like, love, celebrate) on the ad."
        type:
          - "null"
          - number
      registrations:
        description: "Total registrations completed through the ad."
        type:
          - "null"
          - number
      sends:
        description: "Number of messages sent through the ad."
        type:
          - "null"
          - number
      shares:
        description: "Total shares generated by the ad."
        type:
          - "null"
          - number
      start_date:
        description: "Start date of the ad analytics data."
        type:
          - "null"
          - string
        format: "date"
      talentLeads:
        description: "Number of leads related to talent acquisition."
        type:
          - "null"
          - number
      textUrlClicks:
        description: "Clicks on text URLs within the ad."
        type:
          - "null"
          - number
      totalEngagements:
        description: "Total number of engagements on the ad."
        type:
          - "null"
          - number
      validWorkEmailLeads:
        description: "Leads generated through valid work emails."
        type:
          - "null"
          - number
      videoCompletions:
        description: "Number of times videos were watched till completion."
        type:
          - "null"
          - number
      videoFirstQuartileCompletions:
        description: "Completions for first quartile of video views."
        type:
          - "null"
          - number
      videoMidpointCompletions:
        description: "Completions for midpoint of video views."
        type:
          - "null"
          - number
      videoStarts:
        description: "Total video starts initiated by users."
        type:
          - "null"
          - number
      videoThirdQuartileCompletions:
        description: "Completions for third quartile of video views."
        type:
          - "null"
          - number
      videoViews:
        description: "Total views of videos in the ad."
        type:
          - "null"
          - number
      viralCardClicks:
        description: "Clicks on interactive card components in viral distribution."
        type:
          - "null"
          - number
      viralCardImpressions:
        description: "Impressions of interactive cards in viral distribution."
        type:
          - "null"
          - number
      viralClicks:
        description: "Total clicks in viral distribution of the ad."
        type:
          - "null"
          - number
      viralCommentLikes:
        description: "Likes received on comments in viral distribution."
        type:
          - "null"
          - number
      viralComments:
        description: "Number of comments in viral distribution of the ad."
        type:
          - "null"
          - number
      viralCompanyPageClicks:
        description: "Clicks on the company page in viral distribution."
        type:
          - "null"
          - number
      viralDocumentCompletions:
        description: "Complete views of documents in viral distribution."
        type:
          - "null"
          - number
      viralDocumentFirstQuartileCompletions:
        description: "First quartile completions of documents in viral distribution."
        type:
          - "null"
          - number
      viralDocumentMidpointCompletions:
        description: "Midpoint completions of documents in viral distribution."
        type:
          - "null"
          - number
      viralDocumentThirdQuartileCompletions:
        description: "Third quartile completions of documents in viral distribution."
        type:
          - "null"
          - number
      viralDownloadClicks:
        description: "Clicks on downloads in viral distribution of the ad."
        type:
          - "null"
          - number
      viralExternalWebsiteConversions:
        description: "External website conversions in viral distribution."
        type:
          - "null"
          - number
      viralExternalWebsitePostClickConversions:
        description: "Post-click conversions on external websites in viral distribution."
        type:
          - "null"
          - number
      viralExternalWebsitePostViewConversions:
        description: "Post-view conversions on external websites in viral distribution."
        type:
          - "null"
          - number
      viralFollows:
        description: "Follows generated in viral distribution of the ad."
        type:
          - "null"
          - number
      viralFullScreenPlays:
        description: "Fullscreen video plays in viral distribution."
        type:
          - "null"
          - number
      viralImpressions:
        description: "Total impressions in viral distribution of the ad."
        type:
          - "null"
          - number
      viralJobApplications:
        description: "Job applications initiated in viral distribution."
        type:
          - "null"
          - number
      viralJobApplyClicks:
        description: "Clicks on apply job button in viral distribution of the ad."
        type:
          - "null"
          - number
      viralLandingPageClicks:
        description: "Clicks on landing page in viral distribution."
        type:
          - "null"
          - number
      viralLikes:
        description: "Total likes in viral distribution of the ad."
        type:
          - "null"
          - number
      viralOneClickLeadFormOpens:
        description: "One-click lead form opens in viral distribution."
        type:
          - "null"
          - number
      viralOneClickLeads:
        description: "Leads generated in one click in viral distribution."
        type:
          - "null"
          - number
      viralOtherEngagements:
        description: "Other engagements in viral distribution of the ad."
        type:
          - "null"
          - number
      viralPostClickJobApplications:
        description: "Job applications initiated post-clicking in viral distribution."
        type:
          - "null"
          - number
      viralPostClickJobApplyClicks:
        description: "Clicks on apply job button post-clicking in viral distribution."
        type:
          - "null"
          - number
      viralPostClickRegistrations:
        description: "Registrations completed post-clicking in viral distribution."
        type:
          - "null"
          - number
      viralPostViewJobApplications:
        description: "Job applications initiated post-viewing in viral distribution."
        type:
          - "null"
          - number
      viralPostViewJobApplyClicks:
        description: "Clicks on apply job button post-viewing in viral distribution."
        type:
          - "null"
          - number
      viralPostViewRegistrations:
        description: "Registrations completed post-viewing in viral distribution."
        type:
          - "null"
          - number
      viralReactions:
        description: "Total reactions in viral distribution of the ad."
        type:
          - "null"
          - number
      viralRegistrations:
        description: "Total registrations in viral distribution of the ad."
        type:
          - "null"
          - number
      viralShares:
        description: "Total shares in viral distribution of the ad."
        type:
          - "null"
          - number
      viralTotalEngagements:
        description: "Total engagements in viral distribution of the ad."
        type:
          - "null"
          - number
      viralVideoCompletions:
        description: "Completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoFirstQuartileCompletions:
        description: "First quartile completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoMidpointCompletions:
        description: "Midpoint completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoStarts:
        description: "Total video starts in viral distribution of the ad."
        type:
          - "null"
          - number
      viralVideoThirdQuartileCompletions:
        description: "Third quartile completions of videos in viral distribution."
        type:
          - "null"
          - number
      viralVideoViews:
        description: "Total views of videos in viral distribution of the ad."
        type:
          - "null"
          - number
      pivot:
        type:
          - "null"
          - string
      sponsoredCreative:
        type:
          - "null"
          - string

  ad_impression_device_analytics:
    $schema: "http://json-schema.org/draft-07/schema#"
    type:
      - "null"
      - object
    title: "Ad Impression Device Analytics"
    additionalProperties: true
    properties:
      actionClicks:
        description: "The number of clicks on action buttons in the ad."
        type:
          - "null"
          - number
      adUnitClicks:
        description: "The number of clicks on ad unit components."
        type:
          - "null"
          - number
      approximateMemberReach:
        description: "An approximation of unique ad impressions."
        type:
          - "null"
          - number
      cardClicks:
        description: "The number of clicks on interactive card elements."
        type:
          - "null"
          - number
      cardImpressions:
        description: "The number of times interactive cards were displayed."
        type:
          - "null"
          - number
      clicks:
        description: "Total number of clicks on the ad."
        type:
          - "null"
          - number
      commentLikes:
        description: "The count of likes on comments related to the ad."
        type:
          - "null"
          - number
      comments:
        description: "The number of comments on the ad."
        type:
          - "null"
          - number
      companyPageClicks:
        description: "Clicks on the company page associated with the ad."
        type:
          - "null"
          - number
      conversionValueInLocalCurrency:
        description: "Conversion value in the local currency."
        type:
          - "null"
          - number
      costInLocalCurrency:
        description: "Cost of ad campaign in the local currency."
        type:
          - "null"
          - number
      costInUsd:
        description: "Cost of ad campaign in USD."
        type:
          - "null"
          - number
      documentCompletions:
        description: "Number of completions for document views."
        type:
          - "null"
          - number
      documentFirstQuartileCompletions:
        description: "Completions for first quartile of document views."
        type:
          - "null"
          - number
      documentMidpointCompletions:
        description: "Completions for midpoint of document views."
        type:
          - "null"
          - number
      documentThirdQuartileCompletions:
        description: "Completions for third quartile of document views."
        type:
          - "null"
          - number
      downloadClicks:
        description: "Clicks on download links in the ad."
        type:
          - "null"
          - number
      end_date:
"""
