"""Searchable copy of airbyte-integrations/connectors/source-facebook-marketing/erd/confirmed_relationships.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-marketing/erd/confirmed_relationships.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "streams": [
    {
      "name": "ad_sets",
      "relations": {
        "account_id": "ad_account.id",
        "campaign_id": "campaigns.id"
      }
    },
    {
      "name": "ads",
      "relations": {
        "adset_id": "ad_sets.id"
      }
    },
    {
      "name": "ads_insights",
      "relations": {
        "adset_id": "ad_sets.id"
      }
    }
  ]
}
"""
