"""Searchable copy of airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/shared/ads_image_crops.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/shared/ads_image_crops.json'
PART = 1
TOTAL_PARTS = 1

CONTENT = """\
{
  "properties": {
    "100x100": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    },
    "100x72": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    },
    "191x100": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    },
    "400x150": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    },
    "400x500": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    },
    "600x360": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    },
    "90x160": {
      "items": {
        "items": {
          "type": ["null", "integer"]
        },
        "type": ["null", "array"]
      },
      "type": ["null", "array"]
    }
  },
  "type": ["null", "object"]
}
"""
