"""Searchable copy of airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/shared/ads_action_stats.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/shared/ads_action_stats.json'

CONTENT = """\
{
  "type": ["null", "array"],
  "items": {
    "type": ["null", "object"],
    "properties": {
      "1d_click": {
        "type": ["null", "number"]
      },
      "7d_click": {
        "type": ["null", "number"]
      },
      "28d_click": {
        "type": ["null", "number"]
      },
      "1d_view": {
        "type": ["null", "number"]
      },
      "1d_ev": {
        "type": ["null", "number"]
      },
      "incrementality": {
        "type": ["null", "number"]
      },
      "action_destination": {
        "type": ["null", "string"]
      },
      "action_target_id": {
        "type": ["null", "string"]
      },
      "action_type": {
        "type": ["null", "string"]
      },
      "value": {
        "type": ["null", "number"]
      },
      "lead": {
        "type": ["null", "number"]
      }
    }
  }
}
"""
