"""Searchable copy of airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/shared/ads_histogram_stats.json (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/shared/ads_histogram_stats.json'

CONTENT = """\
{
  "type": ["null", "array"],
  "items": {
    "type": ["null", "object"],
    "properties": {
      "action_type": {
        "type": ["null", "string"]
      },
      "value": {
        "type": ["null", "array"],
        "items": {
          "type": ["null", "integer"]
        }
      }
    }
  }
}
"""
