"""Mirror non-code reference files into searchable/ as Python string modules.

The local code-search corpus only indexes code files, so YAML manifests, JSON
schemas and Markdown docs would be invisible. Each such file is copied verbatim
into a .py module under searchable/, keeping its original path, so its field
names, endpoints and prose become searchable. The originals stay untouched.

Run from the repo root:  python3 tools/make_searchable.py
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "searchable"
SUFFIXES = {".yaml", ".yml", ".json", ".md"}
SKIP_DIRS = {".git", "searchable", "tools", "unit_tests", "integration_tests", "sample_files"}
SKIP_NAMES = {"acceptance-test-config.yml", "AGENTS.md", "CLAUDE.md", "CONTRIBUTING.md"}
MAX_BYTES = 500_000  # generated catalogs above this just duplicate the schemas


def wanted(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if rel.parts[0] == "README.md" or path.suffix not in SUFFIXES:
        return False
    if SKIP_DIRS.intersection(rel.parts) or path.name in SKIP_NAMES:
        return False
    return path.stat().st_size <= MAX_BYTES


def to_module(text: str, source: str) -> str:
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return (
        f'"""Searchable copy of {source} (generated by tools/make_searchable.py; do not edit)."""\n\n'
        f"SOURCE_PATH = {source!r}\n\n"
        f'CONTENT = """\\\n{body}"""\n'
    )


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    count = 0
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or not wanted(path):
            continue
        rel = path.relative_to(ROOT)
        target = OUT / rel.parent / (re.sub(r"[^0-9A-Za-z_]", "_", path.name) + ".py")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(to_module(path.read_text(encoding="utf-8"), rel.as_posix()), encoding="utf-8")
        count += 1
    print(f"wrote {count} searchable modules to {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
