"""Mirror non-code reference files into searchable/ as Python string modules.

The local code-search corpus only indexes code files, so YAML manifests, JSON
schemas and Markdown docs would be invisible. Each such file is copied verbatim
into a .py module under searchable/, keeping its original path, so its field
names, endpoints and prose become searchable. The originals stay untouched.

Run from the repo root:  python3 tools/make_searchable.py
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "searchable"
SUFFIXES = {".yaml", ".yml", ".json", ".md"}
SKIP_DIRS = {".git", "searchable", "tools", "unit_tests", "integration_tests", "sample_files"}
SKIP_NAMES = {"acceptance-test-config.yml", "AGENTS.md", "CLAUDE.md", "CONTRIBUTING.md"}
MAX_BYTES = 500_000  # generated catalogs above this just duplicate the schemas
# The corpus stores but does not search very long files (seen at ~3,000 lines),
# so larger sources are split into parts of roughly 1,200 lines.
PART_BYTES = 40_000
# The corpus skips anything under a docs/ folder, so docs get a different prefix.
RENAMED_DIRS = {"docs": "connector_docs"}


def wanted(path: Path) -> bool:
    rel = path.relative_to(ROOT)
    if rel.parts[0] == "README.md" or path.suffix not in SUFFIXES:
        return False
    if SKIP_DIRS.intersection(rel.parts) or path.name in SKIP_NAMES:
        return False
    return path.stat().st_size <= MAX_BYTES


def split_lines(text: str, limit: int) -> list[str]:
    """Split text into consecutive chunks of at most ~limit bytes, on line boundaries."""
    parts: list[str] = []
    current: list[str] = []
    size = 0
    for line in text.splitlines(keepends=True):
        line_size = len(line.encode("utf-8"))
        if current and size + line_size > limit:
            parts.append("".join(current))
            current, size = [], 0
        current.append(line)
        size += line_size
    if current or not parts:
        parts.append("".join(current))
    return parts


def to_module(text: str, source: str, part: int, total: int) -> str:
    body = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    label = f" (part {part} of {total})" if total > 1 else ""
    return (
        f'"""Searchable copy of {source}{label} (generated by tools/make_searchable.py; do not edit)."""\n\n'
        f"SOURCE_PATH = {source!r}\n"
        f"PART = {part}\n"
        f"TOTAL_PARTS = {total}\n\n"
        f'CONTENT = """\\\n{body}"""\n'
    )


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    count = 0
    for path in sorted(ROOT.rglob("*")):
        if not path.is_file() or not wanted(path):
            continue
        rel = path.relative_to(ROOT)
        out_dir = OUT.joinpath(*(RENAMED_DIRS.get(p, p) for p in rel.parent.parts))
        out_dir.mkdir(parents=True, exist_ok=True)
        stem = re.sub(r"[^0-9A-Za-z_]", "_", path.name)
        chunks = split_lines(path.read_text(encoding="utf-8"), PART_BYTES)
        for i, chunk in enumerate(chunks, start=1):
            name = f"{stem}.py" if len(chunks) == 1 else f"{stem}_part{i}.py"
            (out_dir / name).write_text(to_module(chunk, rel.as_posix(), i, len(chunks)), encoding="utf-8")
            count += 1
    print(f"wrote {count} searchable modules to {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
