"""Searchable copy of airbyte-integrations/connectors/source-instagram/manifest.yaml (part 2 of 2) (generated by tools/make_searchable.py; do not edit)."""

SOURCE_PATH = 'airbyte-integrations/connectors/source-instagram/manifest.yaml'
PART = 2
TOTAL_PARTS = 2

CONTENT = """\
        description: The biography or description provided by the user in their profile.
        type:
          - "null"
          - string
      ig_id:
        description: The Instagram ID associated with the user's account.
        type:
          - "null"
          - integer
      followers_count:
        description: The number of followers the user has on Instagram.
        type:
          - "null"
          - integer
      follows_count:
        description: The number of accounts that the user follows on Instagram.
        type:
          - "null"
          - integer
      media_count:
        description: The total number of media items (posts) uploaded by the user.
        type:
          - "null"
          - integer
      name:
        description: The name displayed on the user's Instagram account.
        type:
          - "null"
          - string
      profile_picture_url:
        description: The URL to the user's profile picture.
        type:
          - "null"
          - string
      username:
        description: The username used by the user to log in to their Instagram account.
        type:
          - "null"
          - string
      website:
        description: The website link provided by the user on their Instagram profile.
        type:
          - "null"
          - string
    required:
      - id
  UserLifetimeInsights:
    type: object
    $schema: http://json-schema.org/schema#
    additionalProperties: true
    properties:
      page_id:
        description: The identifier of the Instagram page associated with the insights
        type:
          - "null"
          - string
      business_account_id:
        description: The identifier of the business account to which the insights belong
        type:
          - "null"
          - string
      breakdown:
        description: The breakdown of the insights data, such as age, gender, location, etc.
        type:
          - "null"
          - string
      metric:
        description: The specific metric or measure tracked in the insights data
        type:
          - "null"
          - string
      value:
        description: The actual value of the metric for the given breakdown and page
        type:
          - "null"
          - object
    required:
      - business_account_id
      - breakdown
  Stories:
    type: object
    $schema: http://json-schema.org/schema#
    additionalProperties: true
    properties:
      business_account_id:
        description: The ID of the business account associated with the story.
        type:
          - "null"
          - string
      page_id:
        description: ID of the page associated with the story.
        type:
          - "null"
          - string
      caption:
        description: The caption associated with the story.
        type:
          - "null"
          - string
      id:
        description: Unique ID of the story.
        type:
          - "null"
          - string
      ig_id:
        description: Instagram ID of the story.
        type:
          - "null"
          - string
      like_count:
        description: Number of likes on the story.
        type:
          - "null"
          - integer
      media_type:
        description: Type of media in the story (image, video, etc.).
        type:
          - "null"
          - string
      media_product_type:
        description: Product type associated with the media in the story.
        type:
          - "null"
          - string
      media_url:
        description: URL of the media in the story.
        type:
          - "null"
          - string
      owner:
        description: The user who owns the story.
        type:
          - "null"
          - object
        properties:
          id:
            description: ID of the owner of the story.
            type:
              - "null"
              - string
      permalink:
        description: Permanent link to the story.
        type:
          - "null"
          - string
      shortcode:
        description: Shortcode identifier of the story.
        type:
          - "null"
          - string
      thumbnail_url:
        description: URL of the thumbnail of the media in the story.
        type:
          - "null"
          - string
      timestamp:
        description: Timestamp when the story was posted.
        type:
          - "null"
          - string
        format: date-time
        airbyte_type: timestamp_with_timezone
      username:
        description: Username associated with the story.
        type:
          - "null"
          - string
    required:
      - id
  StoryInsights:
    type: object
    $schema: http://json-schema.org/schema#
    additionalProperties: true
    properties:
      business_account_id:
        description: The unique identifier of the business account associated with the story insights.
        type:
          - "null"
          - string
      page_id:
        description: The unique identifier of the associated page where the story was posted.
        type:
          - "null"
          - string
      id:
        description: The unique identifier of the story insights record.
        type:
          - "null"
          - string
      reach:
        description: The number of unique accounts that viewed the story.
        type:
          - "null"
          - integer
      replies:
        description: The number of replies or interactions generated by the story.
        type:
          - "null"
          - integer
      follows:
        description: The number of accounts that started to follow the account.
        type:
          - "null"
          - integer
      profile_visits:
        description: The number of times the profile was visited.
        type:
          - "null"
          - integer
      shares:
        description: The number of times the story has been shared.
        type:
          - "null"
          - integer
      total_interactions:
        description¨: The number of replies and shares of the story.
        type:
          - "null"
          - integer
      views:
        description: The number of times the story has been viewed.
        type:
          - "null"
          - integer
  UserInsights:
    type: object
    $schema: http://json-schema.org/schema#
    additionalProperties: true
    properties:
      page_id:
        description: The unique identifier for the user's Instagram page.
        type:
          - "null"
          - string
      business_account_id:
        description: The unique identifier for the user's business account.
        type:
          - "null"
          - string
      date:
        description: The date and time the insights data was fetched.
        type:
          - "null"
          - string
        format: date-time
        airbyte_type: timestamp_with_timezone
      follower_count:
        description: The total number of followers for the user's account.
        type:
          - "null"
          - integer
      reach:
        description: The total number of unique accounts that have seen the user's content.
        type:
          - "null"
          - integer
      reach_week:
        description: The total reach in the last week.
        type:
          - "null"
          - integer
      reach_days_28:
        description: The total reach in the last 28 days.
        type:
          - "null"
          - integer
      online_followers:
        description: The number of followers who are currently online.
        type:
          - "null"
          - object
  Api:
    type: object
    $schema: http://json-schema.org/schema#
    additionalProperties: true
    properties:
      account:
        type:
          - object
          - "null"
        properties:
          business_account_id:
            type:
              - string
              - "null"
          page_id:
            type:
              - string
              - "null"
      id:
        type: string
    required:
      - id
"""
